### ISSUE TITLE
InventoryDetailsView "Calibration Coefficient History" Tab does not work if view accessed via link

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#109]
The "Calibration Coefficient History" tab of an InventoryDetailsView page works fine when accessed from the Inventory nav-tree.

However, if the view is accessed via a link, say, from Search, the "Calibration Coefficient History" tab does not populate. 

The workaround is, from a linked-to view, find the inventory item in question in the nav-tree, and click on it. This allows the tab to populate again properly. 

I notice that the url for inventory-details-view is terminated with a slash "/" if linked-to, but not if accessed thru the nav-tree. Dunno if that's at all relevant.

**Comment by sbatchelder** [comment]
From a search-link
![image](https://user-images.githubusercontent.com/44208509/88229117-3526df00-cc3e-11ea-9837-d69ca0c3fef1.png)

after clicking on the relevant nav-tree element
![image](https://user-images.githubusercontent.com/44208509/88229048-1c1e2e00-cc3e-11ea-81b6-3eff76f8a574.png)

**Comment by cahearn** [comment]
Looks good!  Tested on Testing...
