### ISSUE TITLE
Change "Approve" button to "Unapprove" after a Reviewer has approved an event

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#117]
Change the "Approve" button to "Unapprove" after a Reviewer has approved an event and is moved to the Approvers list. (Right now the "Approve" button just stays there after the user has already approved, and it does nothing if clicked again.)
If a user then Unapproves the event, they should be moved back to the Reviewers list, and if the number of Approvers drops below 2, the event should have the green "Approved" indicator (next to the event date) removed.

![Screenshot from 2020-08-03 11-50-23](https://user-images.githubusercontent.com/11924613/89201480-8bb9e480-d57f-11ea-9a7f-faf255805a98.png)

**Comment by joannekoch** [comment]
Enhancement completed.
