### ISSUE TITLE
Allow removal of Reviewers

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#126]
On Staging (v1.5)...

Allow removal of Reviewers for the Reviewers list. Right now, once a Reviewer has been added, there is no way to remove them.

**Comment by cahearn** [comment]
Looks good!  Still a bit tweaky, in that if a reviewer has approved the removal does not go through upon update.  Instead, the original reviewer list re-populates with no approvals.  At that point removals from the list of reviewers work as expected.  Tested on Testing.
