### ISSUE TITLE
Doubling of "Add" and "Remove" Buttons at Part Template "Configs/Consts" Entry

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#131]
If you "Edit Configurations/Constants" back on the Part Template level after values have been entered for Inventory Items, the "Add" and "Remove" buttons are doubled, a new config or const is added and the Template is updated.

![RDB_Config_Bug](https://user-images.githubusercontent.com/14059724/90955016-ceb4fc80-e447-11ea-947a-951896d78cd1.png)

**Comment by cahearn** [comment]
I'm still finding this error, but Mario has been unable to recreate it.  Potentially related to bad Staging data.  Happy to proceed. with current version.

**Comment by spetillo** [comment]
This looks OK with the CTDBP-F & CTDMO-Q Part Templates on Staging. I think this may be a Staging DB quirk with certain Parts, as @cahearn mentioned.

@cahearn What part were you looking at?

**Comment by spetillo** [comment]
Hold the boat! I just found this as I was editing the Calibrations on the CTDBP-F part template. I had already added "cal3" earlier without seeing this, then when I went to add another Cal Name ("cal1"), I got the doubling, too.:

![Screenshot from 2020-08-29 22-40-57](https://user-images.githubusercontent.com/11924613/91650094-25729580-ea49-11ea-8f43-10f5e4531622.png)

**Comment by cahearn** [comment]
Found several examples of the doubling
![image](https://user-images.githubusercontent.com/14059724/91899928-e3756980-ec6b-11ea-9b22-a0ad2d266a53.png)

**Comment by MarioCarloni** [comment]
U am unable to duplicatr this issue from the same Part using Chrome and Firefox. What OS and browser are you running?

**Comment by cahearn** [comment]
I'm using Windows 10, Firefox 80.0 (80?!?! 80's a thing?!?  Doesn't seem right)

**Comment by rhmunier** [comment]
I am not seeing this in the config/const anymore but I am still seeing it in calibrations.  Double add/ remove for add calibration, triple for edit.

**Comment by cahearn** [comment]
Encountered this on the first part I tested on new testing server

![image](https://user-images.githubusercontent.com/14059724/92021226-74f5e180-ed27-11ea-9b8f-a60ef17a2361.png)

**Comment by MarioCarloni** [comment]
Running the latest version of both Chrome and Firefox, I have tried adding/editing Calibrations, Configs, and Constant Names on the Part Template level, using several instances of ADCPS, CTDBP, OPTAA, and NUTNR Parts, and have not been able to duplicate this issue. 

I've tried running this in both Windows and Ubuntu with similar results.

**Comment by ethanandrews** [comment]
I'm seeing the same doubling of the delete button as Connor in Firefox: https://rdb-testing.whoi.edu/parts/839

My initial assumption is that is a Javascript issue with how that delete button is being loaded by jQuery.

**Comment by ethanandrews** [comment]
@MarioCarloni I messed around quickly with the JS code on the template page (`part_confname_form.html`), and if I comment out the extra config lines like this, everything seems to work fine. Is there a reason you need those extra attributes?

```
$(document).ready(function() {

            // Handles CoefficientValueSet form instance generation
            $('.conf_name-form tbody tr').formset({
                prefix: 'config_names',
                addText: 'Add Configurations/Constants',
                //deleteContainerClass: 'delete-here',
                deleteText: 'Remove',
                //added: function(row) {
                //    let remove_button = row.find('.delete-row');
                //}
            });
        });
```

**Comment by MarioCarloni** [comment]
Yes, the container class purpose is to house the remove button within a centered <td> tag. It otherwise will attach, off-centered, to the last child element within the row.

**Comment by ethanandrews** [comment]
@cahearn @rhmunier I think we've now got a fix in for the Firefox bug double buttons. Can you guys please give it a test?

**Comment by cahearn** [comment]
Tested Good!  I tried all the typical routes that I found this error with before and couldn't re-create it.  I'd call this one fixed!

**Comment by cahearn** [comment]
Uh Oh, just found this.  First click of "Add Calibration" was normal and I entered "cal2".  Without leaving the page, a second click of "Add Calibration" button produced the doubling as shown, without the "cal3" text.  Subsequent "Add Calibration" clicks added 

![image](https://user-images.githubusercontent.com/14059724/92276274-ace35d00-eebe-11ea-99af-0e46f11b4d55.png)

**Comment by ethanandrews** [comment]
Love this bug! Ok, I've got a new fix up on staging and testing to hopefully get rid of this thing. @cahearn @rhmunier Please test this out AGAIN and see if we actually got it this time.

**Comment by cahearn** [comment]
I'm not seeing it anymore.  I think you squashed it, but I'll keep trying until we reach broader consensus.
