### ISSUE TITLE
Incorrect Labels for Constant and Configuration Entry Forms

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#132]
When selecting "Add Constants" or "Add Configurations" from "Choose Action" at Inventory Item level, the form has labeling that is incorrect.  Constants form has "Add Configurations" at top, "Configuration/Constant(s)" above entries, and "Add Configurations" on button (see screenshot below for this example).  Configurations form has "Configuration/Constant(s)" above entries.

![image](https://user-images.githubusercontent.com/14059724/90956353-c662be80-e453-11ea-95c7-f3557590c2bc.png)

**Comment by cahearn** [comment]
Fix on Staging server has resolved this issue.  Thanks for taking care of this detail while dealing with larger efforts!

**Comment by spetillo** [comment]
I also checked this on Staging. Looks good!
