### ISSUE TITLE
Errors Entering/Editing Configurations

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#133]
Entered Configurations/Constants on a Part Template.  Initially able to set Configurations on Assembly Template level, but couldn't access on the Inventory Level (see below). 
![image](https://user-images.githubusercontent.com/14059724/90979730-178eb300-e525-11ea-8693-bed97ce0add0.png)

Now trying to edit on Assembly Template causes this error:
![image](https://user-images.githubusercontent.com/14059724/90979747-35f4ae80-e525-11ea-9118-7a4eb60c5e8b.png)

**Comment by cahearn** [comment]
Still finding this error.

Also had this happen on the Constants Edit form.  Happened once on parts that had previous problems, haven't been able to recreate:
![image](https://user-images.githubusercontent.com/14059724/91313281-35595380-e783-11ea-993d-52494d61a4a1.png)

**Comment by cahearn** [comment]
Current Fix on Staging appears to have resolved this issue.  Haven't been able to re-create the error.  Great Job!

**Comment by spetillo** [comment]
Also no errors on this throughout my testing today, so we're good!
