### ISSUE TITLE
Add Warning When Editing Configurations/Constants with Existing Records

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#134]
Not sure what the best approach would be here.  Perhaps a warning similar to the one on Assembly Templates, which warns the user when an Assembly Templates is referenced by actual Builds in Inventory.

**Comment by cahearn** [comment]
Great star.  Warnings are generated for attempted deletions (fora Calibrations as well, which wasn't originally included here).  But I didn't see warnings for general edits to the CCCs (ie changes to name, etc.)  Could those be added?  Would it be a pain?

Screenshot below shows the results of trying to delete a Constant with existing records.  Similar warnings appear for Configs and Calibrations.

![image](https://user-images.githubusercontent.com/14059724/133492063-1758cb91-7b7c-4ce4-af8d-2b5cc1172897.png)

**Comment by joannekoch** [comment]
Warnings for general edits to Configurations & Constants and Calibrations have been implemented successfully.
