### ISSUE TITLE
Edits to Configurations/Constants on Part Templates Makes Future Edits to Existing Default Data Inaccessible

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#135]
As I've seen it, existing data is not affected by changes to the Configs/Consts.  The complication comes when trying to update the Config Defaults on the Assembly Template or the Const Defaults on the Part Template; the Edit form populates with the new C/C, with no option to retain the older integration.  Not imagined to be a common need, but this may be an issue down the line, potentially affecting entire instrument class/series groups

**Comment by cahearn** [comment]
This changes seems to have made the situation worse.  Now, when Configurations/Constants are edited or removed at the Part Template level, the existing records are affect, editing or removing the values of the associated Configs/Consts.

**Comment by spetillo** [comment]
Hmm, ok, I saw that the other day while testing and separately added ticket #147 for it.

**Comment by cahearn** [comment]
I see no change in behavior from this fix.  Still finding that edits to C/C Defaults auto-populate when editing existing records, with no option to retain the existing values.  Also, removing C/C/C names from the Part Template removes the existing records associated with the removed names from History displays and from Calibrations Search results.  (Side note:  Constants/Configurations Search doesn't seem to be working the new C/C names I've entered)

**Comment by MarioCarloni** [comment]
This is related to #147:

"That is expected behavior for now. Calibration Events are the housing for Names and Coefficients. The Calibration Events containing Name attributes of removed Part Template Calibration Names are empty, but the Event will be shown from the Coefficient History tab, as an Event technically exists. This is in preparation for the Deprecation feature. It will ensure that respective Coefficient Values / Notes remain editable from their particular Name / Event instance"

**Comment by cahearn** [comment]
Per conversation with S. Petillo, we should consider moving to an Editing scheme where current data is listed in a column for entry and a separate column to display the defaults being pulled in.  This will enable better control of existing records during the editing process and avoids complications posed by the current method of auto-populating defaults, which overwrites historical values.

**Comment by spetillo** [comment]
This ticket appears to be solved. Config/Constant Values in existing Events (while either editing those values or just viewing them) do not get overwritten when Config/Constant Defaults are updated.
