### ISSUE TITLE
Time in Field not Properly Captured for Instruments with Post-Date Deployment of Builds

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#137]
When I Deployed a Build to the Field, I entered a date from 2 days ago.  The date picker is not working, so I edited the test of the Date field.  The Time in Field for the Build and Deployment is correct, and updating properly.

![image](https://user-images.githubusercontent.com/14059724/90982149-4ad83e80-e533-11ea-8480-5bba6160c87f.png)

 The Time in Field clocks for the individual Inventory Items are incorrect, appearing to have been deployed in the present instead of 2 days ago, but are updating with passing time.  They lag the Deployment Time in Field by 2 days and 1 minute.

![image](https://user-images.githubusercontent.com/14059724/90982168-64798600-e533-11ea-8de8-abf2a6b9ce50.png)

**Comment by ethanandrews** [comment]
Fixes for this issue are up on staging server for testing. @rhmunier please note as well

**Comment by cahearn** [comment]
Several iterations of Fixes tested on Staging.  I hadn't been checking Time in Field data under the Deployments Tab, adding confusion to our process.
Current Fix on Staging appears to have resolved this issue.  Fabuloso!
