### ISSUE TITLE
Add units to Latitude/Longitude in Edit Deployment page & in History Details

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#138]
Add units (degrees N / degrees E) to Latitude/Longitude in Edit Deployment page & in History Details

**Comment by ethanandrews** [comment]
Just a quick question on this one, mostly from my own lack of knowledge here. As we're using decimal degrees, does the North/East labeling still apply? I mostly deal with geo coordinates in mapping software, and they're usually just labeled with a degree symbol or nothing.

**Comment by spetillo** [comment]
Yes, the direction labeling gives the user reference for which directions are the positive axes, at a minimum, and at a maximum they help keep the user from doing something dumb like entering latitude in the longitude field when you're exhausted and entering data while you're on the ship.... It happens.

We can do this one of two ways: 
1. +/- degrees N and +/- degrees E, _or_
2. + degrees N/S and + degrees E/W

I'd prefer (1), since it's easier to type a "-" sign and leave the direction (N/E) static than to click and select N/S/E/W directions every time.

**Comment by cahearn** [comment]
Looks great for displayed info and under "Edit Deployment Details."  @ethanandrews, Could you add the same description text to the initial Lat/Lon entry, found when using the "Deploy to Field" option?  Thanks!

**Comment by ethanandrews** [comment]
No problem, those labels have been added for “Deploy to Field” option.

**Comment by cahearn** [comment]
Sweet, looks great!  Tested on Staging

![image](https://user-images.githubusercontent.com/14059724/103013468-33be5300-450b-11eb-9ee1-5049710de19f.png)
