### ISSUE TITLE
Add a way to edit the Deployment Number after it is initially set

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#140]

**Comment by ethanandrews** [comment]
@rhmunier @cahearn  Please test out the new "Edit Deployment" functionality, it's up on testing and staging server. It's super fun!

**Comment by rhmunier** [comment]
There is no validation for lat and lon for initial deployment and lon validation is accidentally set to <80 instead of <180.

There are no checks on dates allowing for impossible timelines.  The deployed time is kept track of and correctly added even if a deployment is considered to have a negative duration.

**Comment by ethanandrews** [comment]
Good catch on the lat/long typo. I’m aware of the lack of validation on the full Deployment timelines, ideally we would want to validate this dynamically on data entry, but that’s a tricky JS problem we can look at in 1.5.2. For now, I’m working on adding a standard after submission validation that should be enough for the moment.

**Comment by rhmunier** [comment]
If the lat and/or lon field is blank, the time in field will not update.

**Comment by ethanandrews** [comment]
@rhmunier I can't replicate this, time in field seems to update fine on rdb-testing if I change date with empty lat/long field. Can you confirm this?

> If the lat and/or lon field is blank, the time in field will not update.

**Comment by ethanandrews** [comment]
Ok, fixes for lat/.long and date validations are now up on staging/testing for review!

**Comment by rhmunier** [comment]
Ethan,

I did not see any changes for Lat/Lon validation on testing and either I forgot my password for staging or it got changed in a db rollback so have not tested there yet.  I have not tested date validation yet.

Rob

**Comment by ethanandrews** [comment]
My bad, Rob, I got my testing branches mixed up yesterday. You should see validation changes now.

**Comment by rhmunier** [comment]
It might just be my resolution but the error message for the datetime validation covers up the time section and does not fade.  If that is where the error is the update needs to be canceled and redone or have an intentionally wrong date entered and then corrected with a second update.

**Comment by cahearn** [comment]
Working really well.
Validation for dates (_and times!_) up to Deployment checks out, as do the Lat Lon validations and messages.
I found no issue with the dat/time error message obscuring the fields for entry, but there look to be lots of times and ways this could be encountered.
Two minor issues:
Cruise was left blank at first for the Deployment and thus "Cruise Deployed on" was not available for edit until it received an entry during a state change.
"Cruise recovered" was available for edit when the Build was only "Deployed", too early.

**Comment by cahearn** [comment]
Updates to cover minor issues with Cruise notes checks out.  Looks great!
