### ISSUE TITLE
"Assign Destination" to an instrument results in a blank right-side panel after a location on an Assembly is chosen

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#143]
"Assign Destination" to an instrument results in a blank right-side panel after a location on an Assembly is chosen. Also, I'm not entirely sure what the end result of assigning a destination to an Instrument in Inventory is supposed to be, since this appears to be adding an Inventory item to an Assembly Template location (that is not in Inventory).

**Comment by spetillo** [comment]
To test on Staging: Land > WHOI > Instrument Lab >  FLORT-D - CGINS-FLORTD-01300 > Choose Action > Assign Destination > GI01SUMO - Revision B > [Select either destination]
This is the result right now on v1.5.0:
![Screenshot from 2020-08-29 17-05-29](https://user-images.githubusercontent.com/11924613/91646127-e711b200-ea19-11ea-9918-21c3da95dcb1.png)

**Comment by cahearn** [comment]
Tested good!  Assign Destination for "CGINS-CTDBPP-50075" did not result in blank right-hand side of screen.

As you mentioned Steph, Assign Destination is meant to identify Inventory as meant for an Assembly that doesn't have the desired Build created yet, limiting eventual options for Integration.

**Comment by cahearn** [comment]
> 
> 
> To test on Staging: Land > WHOI > Instrument Lab > FLORT-D - CGINS-FLORTD-01300 > Choose Action > Assign Destination > GI01SUMO - Revision B > [Select either destination]
> This is the result right now on v1.5.0:
> ![Screenshot from 2020-08-29 17-05-29](https://user-images.githubusercontent.com/11924613/91646127-e711b200-ea19-11ea-9918-21c3da95dcb1.png)

Just went back and tested as Steph requested.  New fix checks out with "CGINS-FLORTD-01300".
