### ISSUE TITLE
Fix flashing of hidden Cal/Const/Config tabs on Inventory Items assigned to Builds assigned to Builds

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#145]
When I click on an Inventory Item assigned to a Build, the Cal/Const/Config tabs very briefly appear, and then disappear.

Tested on Staging: 
Sea > Global Irminger Sea > Build SMP - GI01SUMO (Deployed - D11111) > Irminger Riser >  CTDMO-Q - CGINS-CTDMOQ-08523 & CTDMO-Q - CGINS-CTDMOQ-11475

Note that neither of these two Inventory Items have Calibration Names entered for them yet, so the Cal/Const/Config tabs are supposed to be hidden, as opposed to briefly flashing on the screen.

See video here: 
https://drive.google.com/file/d/15f1k3vjs0Ot-l7BIR95a8o8PxY21Mb0W/view?usp=sharing

Update: I have added a Calibration Name to the CTDMO-Q Part Template now, so I now correctly see the Calibration Coefficient History tab added, but the other tabs still flash before being hidden.

**Comment by spetillo** [comment]
Update: In further testing, I added a Cal coefficient to CTDMO-G & CTDMO-Q part templates, and once I added a new Calibration Event to those new Coefficients, the Calibration Coefficient History tab became available, and some old Calibration Events for that Inventory item also now show up (with old Calibration Names that no longer exist). Any old calibrations (that haven't been deleted) should show up regardless of whether there are associated Calibration Names in the Part Template, though this is very much an edge case...

**Comment by cahearn** [comment]
Tested Good with current fix!  Way to go!
