### ISSUE TITLE
Spinning wheel of doom when Copying Calibrations from one part Template to another

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#146]
I could create a new Calibration Name, but couldn't copy the Calibrations from another part.

**Comment by spetillo** [comment]
Note: This happened even when I left the Name field blank at the bottom (though I had the same results with a Name filled out as well, as shown below), so it seems to be an issue with the Copying component. I could add a new Calibration name without trying to Copy anything, so that component still works. I verified that the Part Template I was copying from (CTDBP-C) does have Calibration Names created already.

![Screenshot from 2020-08-29 18-04-37](https://user-images.githubusercontent.com/11924613/91646957-052fe000-ea23-11ea-811f-155d5a8a2a2f.png)

**Comment by cahearn** [comment]
Still getting the error, only when trying to copy Calibrations.  Adding Constants/Configurations is not affected.
The Spinner actually remains at the top of the right-hand side while you continue to navigate Part Templates and the forms that appear as you make different selections within the Templates.  It finally quits once a new action is entered/added/etc.

**Comment by MarioCarloni** [comment]
Testing Notes: Copying Cal/Const/Conf Names from the UpdateView worked as expected, but copying from a new Name set failed.

**Comment by cahearn** [comment]
Tested Good on current Staging version!  Woooo Hooooo!
