### ISSUE TITLE
[OBE? - Staging DB issue with this Part? Please investigate] Fix to allow Edit of Configuration Defaults

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#149]
I can add initial configuration Defaults to an Assembly Template (see first image), but I cannot edit them or add more. (I.e., there are no fields appearing under the Name & Default Value headers. See second image of same Part on the Assembly after clicking "Edit Configuration Defaults".)

![Screenshot from 2020-08-29 21-14-47](https://user-images.githubusercontent.com/11924613/91649012-e2122a00-ea3c-11ea-8d72-9d93f38a8be5.png)
)

![Screenshot from 2020-08-29 21-12-23](https://user-images.githubusercontent.com/11924613/91648983-7af47580-ea3c-11ea-9896-562481d3e98f.png)

**Comment by spetillo** [comment]
**UPDATE**: This works with other Parts, but not this one. I blame the Staging DB being a bit out of whack.

**Comment by MarioCarloni** [comment]
I think this is related to #147, which #153 should resolve.

**Comment by spetillo** [comment]
Tested on Staging with the updated DB, and this works fine. (I also had to add this Part to the Irminger Riser assembly of the old GI AT that is now on the refreshed Staging DB, so that might have been part of the issue as well.)
