### ISSUE TITLE
[OBE? - Staging DB issue with this Part? Please investigate] Allow creation of Configuration Events

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#150]
Right now I can create Config Defaults on a Part attached to an Assembly Template, but I cannot create a Configuration Event. Ability to create and edit Configuration Events should occur once a Build is created, and the Events should be dated by Deployment date (or TBD).

@MarioCarloni I know this functionality has already been implemented in a branch somewhere, but it doesn't appear to be available on v1.5.0 as it stands right now on Staging. Should I expect this to be in v1.5.0? If yes, this is a bug and we should get it in v1.5.0. If no, you can remove the bug tag and change this to go into v1.5.1.

**Comment by spetillo** [comment]
**UPDATE**: This works with other Parts, but not this one. I blame the Staging DB being a bit out of whack.

**Comment by MarioCarloni** [comment]
Related to #147, which #153 should resolve.

**Comment by spetillo** [comment]
Re-tested on Staging. This doesn't seem to be an issue anymore.
