### ISSUE TITLE
Can set Custom Field value for a Part Template to an invalid value

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#167]
When editing a Part Template with a Custom Field, it is possible to set the Custom Field to a value that is not valid for that Custom Field.

**Comment by sbatchelder** [comment]
I'm not terribly familiar with the custom field code so I'm looping Ethan into this. 
I'm going to prioritize other bugs from my code areas first, but if this isn't resolved by Ethan by the time i'm done with mine I'll take a stab at this one.

**Comment by sbatchelder** [comment]
@joannekoch is this still an active issue btw?

**Comment by joannekoch** [comment]
Yes it is still an issue. One example is: I defined a "Condition" Custom Field as a Drop Down field with choices: new, good, fair, junk.

I added a Part Template that is a Part Type with this Custom Field enabled. When I edited the Condition Custom Field for the Part Template, I was able to set it to the value = bad. "Bad" is not one of the drop down field choices.
