### ISSUE TITLE
Add Config/Constants to Electrical Part Types

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ooicgsn-roundabout#169]
Need to add the Config/Constant functionality to Electrical Part Types as well so we can use Constants for the Reference Designator assignments

**Comment by ethanandrews** [comment]
@rhmunier This is ready for testing on rdb-testing

**Comment by cahearn** [comment]
Overall function tests great.  Electrical parts now have access to Constant/Configuration capabilities.

I found some quirkiness in the reviewer function that I don't remember from earlier testing.  Once the initial review list is set, it can not be changed in subsequent edits, despite new selections being accepted from the interface when clicking "Update C_____s".  I _do_ _remember_ this behavior.  However, when trying to update C/C after I have approved, I am only added back to the approver list on every other edit/update.  This may need further explanation, investigation

Also, bummed to stumble onto the doubling bug again, at the Part Template level.  Tweaked slightly from any previous version I remember coming across; now the doubling only occurs on the initial C/C entry, and then on entries made using the second, doubled "Add Configurations/Constants" button.

![image](https://user-images.githubusercontent.com/14059724/94723984-926a9b00-0327-11eb-8414-43ec101337df.png)

**Comment by MarioCarloni** [comment]
Note: You can enable CCC's from the Part Type template by selecting "Enable Configs, Constants, and Calibrations"

**Comment by spetillo** [comment]
@cahearn Please add the Reviewer functionality issue you found as new ticket, or add it to the appropriate existing ticket. The Doubling issue I also saw during testing the addition of Calibration Names, so I created ticket #196. Please add your notes from here to that ticket. 

Once you have added/updated those tickets, we we can close this one out, since this central functionality works.

**Comment by cahearn** [comment]
Roger that!  Doubling issue previously had a ticket: #131 
There's a couple tests of the Reviewer functionality that are ongoing, #113 and #126 .  Probably best to pull all the lingering issues from those into a single Reviewer Review ticket.
