### ISSUE TITLE
When updating Config Defaults after adding a new Config Name, errors are thrown (sometimes)

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#173]
![configuration default error](https://user-images.githubusercontent.com/11924613/93146090-f2243d80-f6bb-11ea-9f94-8c42fd82ea7e.png)
I added the "Reference Designator" Configuration Name to the CTDMO-Q, then assigned the Configuration Default for that Configuration to the CTDMO-Q part at 20 m "Nominal Depth" (Configuration) on the Irminger Riser on GI01SUMO Rev B's Assembly Template. This worked fine.

I then repeated the process to add "Acoustic Modem ID" Configuration Name to the same Part Template (CTDMO-Q), then tried to assign a Configuration Default to it on the same CTDMO-Q on the same Assembly Template as above. This resulted in the errors shown on the screen shot. I'm not sure which of the Config Default fields these errors apply to, but I'm guessing they're the 3 fields that already existed (Legacy Name, Nominal Depth, Reference Designator).

It's strange that I could add the new Reference Designator Configuration Default, but not the Acoustic Modem ID Configuration Default.

**Comment by cahearn** [comment]
Mimicked the additions @spetillo detailed and could not reproduce the error on v1.6.1 on Staging (note that DB data is substantially different now, with a number of Assembly Templates no longer present, including the GI01SUMO Steph used for testing here). 

This passes Testing!  but will keep an eye out given the intermittent nature described.
