### ISSUE TITLE
Automated tests fail with timeout error

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ooicgsn-roundabout#178]
On merging the new release branch into develop for deployemnt, the circleCI automated test build failed with a timeout error. @joannekoch is this related to using both Firefox and Chrome drivers?

<img width="1403" alt="Screen Shot 2020-09-17 at 9 34 45 AM" src="https://user-images.githubusercontent.com/39806262/93477492-16089e80-f8c9-11ea-8757-022fe54c7588.png">

**Comment by joannekoch** [comment]
@ethanandrews this error is related to the inconsistent behavior of Firefox and more specifically (I believe) its Geckodriver. I have removed invoking the Firefox tests on my branch. I suggest we merge the latest changes on my branch which also include new Import/Export Tests.

**Comment by ethanandrews** [comment]
Ok, please PR your branch to the develop branch then.


On Sep 17, 2020, at 9:51 AM, joannekoch <notifications@github.com> wrote:

﻿

@ethanandrews<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fethanandrews&data=02%7C01%7Ceandrews%40whoi.edu%7C631bee34782641be0f8e08d85b10d320%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C637359475102733206&sdata=X9PjihT%2B%2FUWXowRq%2FZYd8z5%2BTtMsHSVEzVGpV7ldtA0%3D&reserved=0> this error is related to the inconsistent behavior of Firefox and more specifically (I believe) its Geckodriver. I have removed invoking the Firefox tests on my branch. I suggest we merge the latest changes on my branch which also include new Import/Export Tests.

**Comment by joannekoch** [comment]
Removed Firefox tests from Automated Tests.

Fixed with Pull Request #179.
