### ISSUE TITLE
Support Import of Calibration Coefficient GitHub CSV's

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#182]
In reference to Trello TASK 25:

Support import of calibration values from CSV files (RDB-AM-101).

Support parsing current GitHub calibration CSV filenames into relevant fields (RDB-AM-102).

**Comment by spetillo** [comment]
@MarioCarloni I entered all of the `CC_` Calibration Names for the Instrument > CTDBP-C Part Template, then tried to import [CGINS-CTDBPC-06841__20110518.csv](https://github.com/oceanobservatories/asset-management/blob/master/calibration/CTDBPC/CGINS-CTDBPC-06841__20110518.csv).

I ended up with an error on the first row (`CC_a0`), saying "Row: 1, Column: 1, 0.001301118 Exceeded Instrument 0-digit decimal place maximum." (first screen shot)

I have the Significant Figures set to 10 on the Calibration Name entry page (second screen shot), so I'm not sure why I'm getting this error. 

Any Ideas?

![Screenshot from 2020-10-14 10-40-23](https://user-images.githubusercontent.com/11924613/96005324-539a1200-0e0a-11eb-8ddd-0c84f7d08a1c.png)
![Screenshot from 2020-10-14 10-40-04](https://user-images.githubusercontent.com/11924613/96005341-572d9900-0e0a-11eb-9981-7dc71605018a.png)

**Comment by spetillo** [comment]
Doh. - Thank you! Import complete. :) I imported a single file, then the remaining 4 files for that instrument. Upon brief inspection, all looks good!

**Comment by spetillo** [comment]
Tested import of  CGINS-OPTAAD-00123 Calibrations. Single, 1D & 2D are all functional. Small learning curve, but very easy and quick to import multiple files for a single S/N instrument and multiple S/N'd instruments at once!

Noting here that we can only import a single instrument type at once, but that's not a huge deal.

@MarioCarloni I tried importing all CTDBPC Calibration CSVs at once, and apparently one of the files has a value that needs >20 Max Calibration Coefficient decimal places (for a value -6.79925987e-012). Can we increase this limit?

Otherwise, looking great with my testing!

**Comment by MarioCarloni** [comment]
Thanks! Increasing the Coefficient decimal places limit shouldn't be an issue.

**Comment by spetillo** [comment]
As per our discussion in the meeting today, let's up it to 32.

**Comment by spetillo** [comment]
Interestingly, (after your latest update to increase the `Max Calibration Coefficient decimal places` limit) I didn't change the `Max Calibration Coefficient decimal places` value (which I had previously set at 20), tried the import again, and it worked without complaint. The number the validation was failing on would have had exactly 20 decimal places, so perhaps this was an edge case?

I am also hoping to test that, if I give it max decimal places that are too low, the validation still gives the error I was correctly getting before. However, I ran into a new bug where I can't copy or enter new Calibration Names on Part Templates, so I can't do another import. Putting in a ticket for that...

**Comment by spetillo** [comment]
Re-tested with CTDBP-C, CTDBP-D, DOSTA-D & DOSTA-J after all bugs were worked out and max decimals upped to 32. Looks great!
