### ISSUE TITLE
Add Cancel Button to Start New Deployment Screen

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#185]
Cancel button is missing on the Start New Deployment Screen. Create a New Build, select it, and navigate to Builld->Choose Action->New Deployment.

**Comment by cahearn** [comment]
Looks Good!
![image](https://user-images.githubusercontent.com/14059724/96013283-171ee400-0e13-11eb-8194-0303dcb730df.png)

**Comment by joannekoch** [comment]
Verified cancel button added. Thank you.
