### ISSUE TITLE
Location is not required on Some Build Deployment Screens causing Spinning Wheel

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#186]
Start New Deployment and Initiate Burn In Screens - Current Location is not required, but when set it to '------', the software hangs with a spinning wheel.

Deploy to Field Screen - Deployment Location defaults to '-----' and is not required, when hit Update Deployment without changing the Location, the software hangs with a spinning wheel.

**Comment by ethanandrews** [comment]
Fixed in 1.7, location field is now required
