### ISSUE TITLE
Remove excess "Remove" & "Add Calibration" buttons when adding/editing Calibration Names

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#196]
This is related to #162, and is still an issue on v1.5.1. Not a huge issue, so this can be fixed for v1.6.1.
I was testing on Staging v1.5.1, with the Instruments > CTDBPC Part Template.
![Screenshot from 2020-10-14 10-30-33](https://user-images.githubusercontent.com/11924613/96003578-5d227a80-0e08-11eb-9e7e-c024dacd4680.png)

**Comment by cahearn** [comment]
Comment from #169 : 

... stumble onto the doubling bug again, at the Part Template level. Tweaked slightly from any previous version I remember coming across; now the doubling only occurs on the initial C/C entry, and then on entries made using the second, doubled "Add Configurations/Constants" button.

![image](https://user-images.githubusercontent.com/14059724/96030917-a388d100-0e2a-11eb-8019-8dea40093ebc.png)

**Comment by cahearn** [comment]
Found this problem persisting for Constants and Configurations on 1.6.0, tested on Staging, & 1.6.1, tested on Testing db.  Not seen in Calibrations... yet

![image](https://user-images.githubusercontent.com/14059724/100005892-a6ff6880-2d97-11eb-848e-e9c279a97426.png)

![image](https://user-images.githubusercontent.com/14059724/100006620-c64ac580-2d98-11eb-83d9-b42e793e700a.png)

**Comment by cahearn** [comment]
Lots of testing, hasn't come back... yet!
Will keep an eye out but this one passes.  Good Work!
