### ISSUE TITLE
Merge all Import functionality into a single UI

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#200]

**Comment by cahearn** [comment]
Tested on v1.6.1 on Staging.  Looks great!, but not sure if all of the functionality @spetillo originally commented for is present.  Pretty sure, just not certain.

![image](https://user-images.githubusercontent.com/14059724/101676973-ef6e8580-3a29-11eb-97be-3e4159cd4fab.png)

**Comment by spetillo** [comment]
Other than Calibration imports (which are working as they have been), I haven't put this through its paces in terms of the actual import _functionality_, but this integrated UI _looks_ fine to me, too!
