### ISSUE TITLE
On Vessel import/creation, allow "Active" and "R2R" fields to be left empty or set as "Unknown" (currently both default to "Yes")

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#210]
Right now there is at least one vessel in the shiplist.csv that has both of these fields empty, but they show up as "Y" in the Vessel list and CSV export from RDB. These should either be left empty (to create an exact CSV export) or set to "Unknown".

Note: shiplist.csv is not actually used by the CI-side software, so these two fields do not need to be booleans.

**Comment by cahearn** [comment]
Looks Great!  Tested on Staging, with repeated imports of fictitious R/V Bosun.  Nice work!
