### ISSUE TITLE
Remove two sets of excess quotes on the Value field for exports, and add ACS- prefix to OPTAA S/Ns

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#211]
1. I'm seeing excess quotes in the DOSTAD  & OPTAAD CSV exports from v1.5.1.

In this screen shot, the file I imported is on the left, and the file I exported is on the right.

![Screenshot from 2020-10-16 17-31-45](https://user-images.githubusercontent.com/11924613/96310708-e3d88280-0fd5-11eb-8cdc-b396d38b2c93.png)

2. We need to add ACS- prefix to OPTAA S/Ns to make the imports = exports

![Screenshot from 2020-10-16 17-43-00](https://user-images.githubusercontent.com/11924613/96311241-0dde7480-0fd7-11eb-9d66-5b6c32206dca.png)

**Comment by cahearn** [comment]
Both issues are fixed for specific CSVs and do not appear elsewhere in my recent testing on Staging.  Good to go!
