### ISSUE TITLE
Conflicting Calibration Significant Figures Entry Error Messages

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#215]
Enter a Significant Figure of 99 for a Part Template Calibration. Get error: Input must be between 0 and 20.

Enter 0 and get error: Ensure this value is greater than or equal to 1.

**Comment by spetillo** [comment]
To add to this, that message should be updated to "Input must be between 0 and 32" if you're running v1.5.1 or newer... Ideally, 32 should be referenced by it's variable in the code for this error message, so that this will dynamically update.

**Comment by joannekoch** [comment]
Testing on v1.7.0, if you enter a Calibration significant value of 32, you get the following error message when it should be,
"Input must be between 1 and 32"

![Capture](https://user-images.githubusercontent.com/65416034/109989124-32ad5d00-7cd6-11eb-81f1-1456d0883b47.PNG)

All other values entered (-1, 33, etc) result in the correct error: Input must be between 1 and 32. Nice work.

**Comment by cahearn** [comment]
Entry of 32 now accepted!

![image](https://user-images.githubusercontent.com/14059724/111521915-1545ad80-8730-11eb-804f-f86250bc84fa.png)
