### ISSUE TITLE
Calibration Data for a Part Template can be created without specifying any data

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#216]
It is possible to create empty Calibration data for a Part Template. 

Select "Create Calibrations" for a Part Template. Select the Reviewers and Select "Add Calibration(s)". Do not specify a template to copy or a calibration name. 

No error message is displayed and a Calibration Event is created with no data.

**Comment by MarioCarloni** [comment]
Sounds good. I'll make another enhancement card.

**Comment by cahearn** [comment]
Oddly enough, I was able to re-create this error on my first try.  I added an empty Calibration event to the VICS Part Template, [here.](https://rdb-testing.whoi.edu/parts/922)  It would be good to have this addressed, but as it doesn't actually break anything, I"d be fine punting this one to a later milestone.

**Comment by cahearn** [comment]
We've got an error message now, with no event allowed or created without the Cal name.  Nice job!

![image](https://user-images.githubusercontent.com/14059724/111522758-f5fb5000-8730-11eb-8f2c-f6ecf739c928.png)
