### ISSUE TITLE
Search on both Name and Username automatically

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#219]
An a situation where one needs to search against users, the query should automatically search both for matching users' Name and Username

This will address (2) from Issue #212 
because the "admin" user has no Name field

**Comment by spetillo** [comment]
@sbatchelder Since the system only ever displays the `user.username` when selecting and displaying the Reviewers and Approvers, can the Reviewers and Approvers Search just be changed to use `user.username` instead of `user.name`? Would that be straightforward to change?

**Comment by sbatchelder** [comment]
@spetillo That would be a straightforward change yes. Would you like the search results column to also display username instead?

**Comment by spetillo** [comment]
@sbatchelder Yep, let's display ursername in the results instead, too.

**Comment by cahearn** [comment]
Generalized search on Name/Username looks great!
For Steph's request (for Reviewer/Approver Search, search on and display username only) it looks like you have limited to user.name instead.  Appears to be consistently applied to Approver/Reviewer searches in Inventory, Cal, Const/Config.
![image](https://user-images.githubusercontent.com/14059724/105663181-9a82b380-5e9f-11eb-9bae-130436ee920c.png)

![image](https://user-images.githubusercontent.com/14059724/105663235-bb4b0900-5e9f-11eb-9a13-04422f327bd1.png)

Possibly too deep with this last bit, but User search returns Name for Approver/Reviewer events

![image](https://user-images.githubusercontent.com/14059724/105664073-cbfc7e80-5ea1-11eb-9fd4-edc9e4d236b4.png)

![image](https://user-images.githubusercontent.com/14059724/105664092-da4a9a80-5ea1-11eb-8c97-2de206841e2b.png)

**Comment by sbatchelder** [comment]
Above update includes: Users can search for name or username in all places now, and in search results names are shown, unless not set, in which case usernames are shown.

**Comment by cahearn** [comment]
As mentioned in previous Wed. RDB Dev meeting, the display format for user names is no longer a concern.
Tested multiple users is various name formats across all Search menus with "User" fields and found consistency in numbers of reults returned for all.  Awesome work!
[Tested on Staging]

![image](https://user-images.githubusercontent.com/14059724/108017818-d95de200-6fe3-11eb-96f2-8e1ad3b4f02c.png)

![image](https://user-images.githubusercontent.com/14059724/108017842-eaa6ee80-6fe3-11eb-90f1-f400ddfe7d7f.png)
