### ISSUE TITLE
Searches against a Datetime field with a Date should return results for that date

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#220]
Many db models have a created_at Datetime Field, eg "2020-10-20 10:20:20"
Currently, to search for objects created on a particular date, one must specify a start and end date, ie >=2020-10-20 & <= 2020-10-21. The full datetime timestamp could be specified, but this is extremely cumbersom.

The search interface should take care of these details automatically. 
This enhancement would apply to other Datetime fields, not just created_at fields

Resolving this issue addresses point 3 of Issue #212

**Comment by spetillo** [comment]
@sbatchelder I'm trying to understand the implementation/incarnation of the datetime fields in RDB...How is the datetime stored in the system? is it a string, or its it a "seconds since epoch" that just displays in the "YYYY-MM-DD hh:mm:ss" format, or something else?

**Comment by sbatchelder** [comment]
@spetillo 
They're stored in django through [Date and Datetime Fields](https://docs.djangoproject.com/en/3.1/ref/models/fields/#datefield) which -in practice when you pull the value out from the database- come out as [python datetime.date and datetime.datetime](https://docs.python.org/3/library/datetime.html#available-types) objects respectively. 

The string representation of these objects as rendered is defined by a format string. A string can be converted to a datetime if the formatting is strict (which is what we currently do on the search form) but an exact match on a datetime field is a bit ridiculous without knowing down to the second the actual value.

**Comment by spetillo** [comment]
@sbatchelder Agreed, that is a bit ridiculous... Let's come back to this next week and brainstorm some more implementation options (I realize there may not be any/many).

**Comment by ethanandrews** [comment]
I ran down the code I’ve used before for filtering a datetime model field by just the mm/dd/yyyy date part. There’s a filter in the Django ORM for this:  `__date`

`set = Inventory.objects.filter(created_at__date=datetime.date(2020,12,8))`

This would return all Inventory objects that have a `created_at` datetime on 12/8/2020, ignoring the time part.

**Comment by cahearn** [comment]
All search categories provide "Date" format option, and helpful error note when not properly input.  Looks Great!
