### ISSUE TITLE
Generate relevant Configuration / Constant Events from Calibration Imports

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#224]
Some instrument data (ADCP, METBK) contains Configuration and Constant Event data, as well as Calibrations. However, the current import functionality does not discern between generating Calibration vs Config/Constant Events.

Create functionality to generate Config and Constant Events from instrument CSV's containing them.

**Comment by cahearn** [comment]
Constant Events only populated when the Constant Names had corresponding Calibration Names, i.e. entered in both lists.

**Comment by MarioCarloni** [comment]
I think I see where the error is occurring, and may be tied with #286 . The new Calibration Name auto-generation logic is creating a Calibration Name for each Config or Constant Name not found, which is interacting the with form validation... I'm currently working towards a solution.

**Comment by MarioCarloni** [comment]
With the reversion of the autogeneration logic, Config/Constant events should be generated via CSV import if relevant Config/Constant Names are first created within the Inventory Part.

**Comment by cahearn** [comment]
I'm finding the same behavior as before.  The Config/Constant Event is only generated if the Config/Constant Names are included in the Calibration Names as well as the Config/Constant Names.  (On Staging, see [METBK Logger](https://ooi-cgrdb-staging.whoi.net/parts/834/) and [CGINS-METLGR-00001](https://ooi-cgrdb-staging.whoi.net/inventory/1546/) where you'll see two uploads for the Cals, but only one for the Configs/Constants, which corresponds to the second Cal upload time.)

**Comment by MarioCarloni** [comment]
I've added a hotfix to allow Config/Constant Event generation via CSV Import without needing Calibration Names added to the Part. However, in 1.6.1, Config/Constant Names must still be entered from the Part template prior to CSV import.

**Comment by cahearn** [comment]
[Tested on Staging]
Looks perfect!  Cals and Configs/Constants properly populate, with C/C/C Names in appropriate lists.  Adding a reviewer at upload, multiple file upload, and note entry all tested great as well.  Fabulous work!
