### ISSUE TITLE
Search for Builds yields ValueError Screen

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#226]
When attempting to Search for Builds, a ValueError screen is thrown on rdb-testing.whoi.edu and release 1.6 in Docker. This is repeatable and happens every time.

<img width="923" alt="ValueError" src="https://user-images.githubusercontent.com/65416034/97316914-a9c27880-1840-11eb-945a-5dec4d862d11.PNG">

**Comment by ethanandrews** [comment]
@joannekoch fix for this is now up on rdb-testing.whoi.edu, please test it out. Thx!

**Comment by joannekoch** [comment]
It is working as expected. Thank you.
