### ISSUE TITLE
Detail Screen Blank after Delete Calibration

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#229]
After Deleting a Calibration for an Inventory or Part Template, the detail information screen is blank for the selected item in the Navtree.

<img width="929" alt="Capture" src="https://user-images.githubusercontent.com/65416034/97907486-5bffb180-1d13-11eb-8cfe-4fdf749ba1ff.PNG">

**Comment by cahearn** [comment]
The update here now causes RDB to deselect the inventory item being worked on when a Calibration is deleted.  Details are accessible when the item is re-selected.  Bug is fixed but it would be better to remain selected on the original inventory item so that work can be continued.  This is the usual and expected behavior in other RDB functions and would be preferable here, unless there are technical reasons for the difference.

**Comment by cahearn** [comment]
@MarioCarloni , would you please look into what it would take to change the deselecting behavior mentioned above?  Thanks!

**Comment by MarioCarloni** [comment]
I should be able to revert the merged delete-view logic above to its original state, and rework the deletion functionality to reload the Inventory detail template.

**Comment by cahearn** [comment]
Awesome improvements.  Inventory side looks nailed!
For the Part Templates, after deleting the Calibration, its record remains in the display although none of the buttons ("Delete," "Approve," "Edit Calibrations") work.  The record is removed after a page refresh or other operation causes reload of the info.

**Comment by MarioCarloni** [comment]
I'm seeing the same behavior locally. Currently looking into a resolution for this.

**Comment by cahearn** [comment]
I'm finding the same behavior still

![image](https://user-images.githubusercontent.com/14059724/103812819-18843500-502d-11eb-8996-00040d617525.png)

**Comment by MarioCarloni** [comment]
From Staging, I'd added and deleted Calibration Names from the VICS part screenshotted above (Part ID 912), CTDBP-E (Part ID 810), and METBK Logger (Part ID 834). Post-deletion, the correct Part was selected from the left tree, with related Part detail template loaded, containing no Calibrations as expected.

Are there certain Parts where this "ghost Calibration" behavior is more apparent?

**Comment by cahearn** [comment]
I have not been able to recreate the issue, despite repeated attempts.  Not quite sure what to say about it at this point.  Clearly intermittent, at best, and a relatively benign issue.
