### ISSUE TITLE
Inventory Part details inaccessible after deleting all Constant Defaults from that Part

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#231]
I broke CTDMO-Q - CGINS-CTDMOQ-08523 Inventory on Staging by deleting the Constant Defaults when I had a Constant Event already created for that Constant Name at the time that I deleted the Default. The way it "broke" is that I can no longer access anything on that inventory item (nothing loads on the right panel when I click on that item in the inventory tree on the left). At this point, I can't edit anything for that Inventory part, and I can't (re)move it from it's current location on the Global Irminger Sea > GI Surface Mooring > GI01SUMO Global... > IRMINGER RISER > CTDMO-Q.

**Comment by cahearn** [comment]
All Good in the Hood!

- CGINS-CTDMOQ-08523 has been fixed and is again fully accessible on Staging!
- Tested the described procedure with CGINS-DOSTAD-00226 and found no errors!
- Additional testing turned up no problems associated with deleting Constant Defaults!!!
