### ISSUE TITLE
Don't return Search results for Part Types with CCCs disabled

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#234]
Related to updates from #180 & #235 : Previously-entered CCC Events will show up in Search, even when the CCCs are disabled for a given Part Type. This isn't particularly an issue, but could be confusing if CCCs were made for some Part Types and then disabled/hidden from viewing & editing, but show up as "phantoms" in a search.

I would suggest doing a check for the CCC Enable/Disable state that gets set in the Edit Part Types page, and hiding (or skipping) the CCCs of the CCC-Disabled part types from the search results.

**Comment by sbatchelder** [comment]
I think I got this completed. release-1.7.0 doesn't exist yet, do I'll just hold on to it in my local branch for now.

**Comment by spetillo** [comment]
@sbatchelder @ethanandrews Can we get this in on v1.6.2 since it's done already?

**Comment by cahearn** [comment]
Created Calibration Coefficient "Enabled" and value "45" for [3705-00047-01-02](https://ooi-cgrdb-staging.whoi.net/inventory/904/) on Staging.  Cal search appeared at first and then disappeared when I disabled the CCC option from the Cable part type.  Interesting to note, the Cal record also disappeared.  Cal record (and proper search return) re-appeared when I subsequently re-enabled CCCs for Cable part type.
Works like a charm!
