### ISSUE TITLE
Fields Missing for Cruise and Vessel (non-CI) Export

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#236]
The following fields are missing for export:

Vessel: Notes

Cruise: Friendly Name, Destination

**Comment by spetillo** [comment]
For **CI-required** Exports, Cruises Friendly Name and Location (I don't see a Destination field) and Vessel Notes should not be included, since they are not columns in the original CI CSV files.

Reference CI Cruise CSV:
https://github.com/oceanobservatories/asset-management/blob/master/cruise/CruiseInformation.csv

Reference CI Vessel CSV:
https://github.com/oceanobservatories/asset-management/blob/master/vessel/shiplist.csv

For more **generic** Exports of the Cruise and Vessel info, however, I agree. The fields @joannekoch noted above should be included.

**Comment by sbatchelder** [comment]
@spetillo @joannekoch 

How do we want to go about this from an interface point of view?
1. Vessel and Cruise export buttons only export non-CI csv's (which include Notes + Friendly Name and Destination fields, respectively). The CI version of these files become exclusively available in the `Export All [CI]` button.
2. Create explicit CI/non-CI download buttons for Vessel and Cruise exports.


[screenshot of the exports page]

![image](https://user-images.githubusercontent.com/44208509/102931421-5f3e3080-446c-11eb-91ae-032eb65f0a2a.png)

**Comment by joannekoch** [comment]
@sbatchelder @spetillo Since I now know more about this issue, I have some thoughts. 

The general workflow is import, then export, and the files should match. Currently we do not have the "formal" ability (see last question below) to Import non-CI Vessels and Cruises so perhaps we don't need the capability to export them. 

Also, other questions arise:  
Would a user ever need to create a mix of both CI and non-CI Vessels and Cruises in a practical sense (the software does not prevent it)? Would we want to create the ability to Import non-CI Vessels and Cruises in the near future? 

You can Import a Github non-CI Vessel file with a Notes column. The import succeeds all the fields are created except for the Notes field. Would this be confusing to the non-CI user?

**Comment by cahearn** [comment]
The various options for export and their associated outputs look spot on!  Great work.  I should note, among several things not output in the non-CI exports here are the newly added URL links.  I think it's the right choice for now.

As to Joanne's questions above, I don't see a practical reason for a mixed, CI/non-CI export.  There's no near-term need to add flexibility and expanded non-CI support to Imports.  I think any non-CI user will need a significant amount of guidance to avoid confusion with the Import/Export functions.

**Comment by sbatchelder** [comment]
@cahearn 
should we remove those non-ci export buttons in that case and make CI-exports the default for that export page?
the alternative for now is to do nothing and leave things as they are (and closing this issue :)

**Comment by cahearn** [comment]
I think we're good to close this.  If we get feedback that they'd prefer some different setup, we'll create a new card for that request.
