### ISSUE TITLE
Add a "Go To [Part/Assembly/Part on an Assembly/Location] Template" button or menu item to everything in Inventory

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#239]
Add a "Go To [Part/Assembly/Part on an Assembly/Location] Template" button or menu item to everything in Inventory (& Builds).

Right now it is a click-intensive process to move between Inventory and Templates, and it involves remembering where in the hierarchy tree you were working in Inventory when you go to the Template side to look for the "origin" of your Part, Assembly, or Part on an Assembly (and this could apply to Location, too). I find myself doing this extremely often, especially when creating and editing CCC Names, Defaults and Events, which are set in Part Templates, Assembly Templates, Parts on Assembly Templates, and in the Inventory & Builds themselves.

**Comment by cahearn** [comment]
Links look and work great!  Inventory items have links, when appropriate, to associated Part Template, Assembly Template designated slot, Current Build and Current Location.  Builds have links to associated Assembly Template and Current Location.  Muchas Gracias!
