### ISSUE TITLE
Remove extra warning modal upon CCC Name Removal

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#240]
From testing #153 (Deprecation feature):
If I Remove a CCC Name, I get two warning modals that say the same thing, except the second has a check box so I can silence the warning. Only one modal (with the check box option) should be shown.

**Comment by MarioCarloni** [comment]
Release 1.6.1 contains fixes related to both the warning modal, and duplicate add/remove buttons, so will move this issue to Review in Progress while 1.6.1 is being tested.

**Comment by cahearn** [comment]
Still an issue on 1.6.0, tested on Staging.  Looks good on 1.6.1, tested on Testing!

**Comment by spetillo** [comment]
I changed the Milestone to v1.6.1 instead of v1.6.0, since that's where the fix got pushed to. NBD. Moving ticket to approved, since it's working on Testing on v1.6.1.

**Comment by cahearn** [comment]
Ahhh, it was a mistake to offer that earlier partial update.  I hadn't put 1.6.1 through extensive testing, just a couple spot checks.  I've found in more thorough testing that the Extra Warning Modal still appears, albeit inconsistently.  Gotta kick this back to In Progress.

Additionally, when remove is clicked, the CCC is removed prior to and despite the warning.  This means the only method to avoid the removal after receiving the warning is to cancel the update.  Not a big deal but we may want to consider adding the option to decline removal within the warning structure, depending on how difficult that is to negotiate with the code

![image](https://user-images.githubusercontent.com/14059724/100015420-ef258780-2da5-11eb-9fb8-1e6e31c8a135.png)

![image](https://user-images.githubusercontent.com/14059724/100015483-06647500-2da6-11eb-8b15-ff80c163cb3b.png)

**Comment by spetillo** [comment]
Right...The modal needs to include a Cancel button.

**Comment by cahearn** [comment]
Still occurring in v1.6.1 on Testing

1st:
![image](https://user-images.githubusercontent.com/14059724/101308990-2e79bc80-3819-11eb-8bea-29b522e613f0.png)

2nd:
![image](https://user-images.githubusercontent.com/14059724/101309014-43565000-3819-11eb-93d4-43683537d1cb.png)

**Comment by MarioCarloni** [comment]
The new functionality should be present on whichever server is running the newest 1.6.1 code. I've pulled and run both my working release-1.6.1 branch and the current release-1.6.1 branch, and both versions populate with the new functionality.

**Comment by cahearn** [comment]
I asked @ethanandrews to check the status of 1.6.1 on Testing.  He rebuilt Testing/Staging containers from current branch and I'm still seeing the extra warning modal on both.  However, the Cancel button is now present, which wasn't there previously.

Bonus Info:  If I check the "Prevent this page..." box in the second warning, click "OK" and "Update C/C," the "Remove" buttons don't work in ensuing "Edit C/C" attempts.

**Comment by cahearn** [comment]
Inconsistently successful now on Staging and Demo.  Testing has been consistently working, but hard to be sure with all the bouncing back and forth.

**Comment by cahearn** [comment]
Following latest v1.6.1 updates (per @ethanandrews @ 15:27) I have seen a full range of behavior on a single Part Template (ADCPS-J) on rdb-testing.

1. First attempt to remove a Config Name yielded a single warning.
2. I canceled and tried again to find that clicking the "Ok" for the single warning quickly flashed the second modal (with the checkbox) as the Config was removed.
3. I canceled again and then found in my next attempt that two warnings populated, both requiring "Ok."

Finally, at some point I have also found that the second warning sometimes requires two clicks to the "Ok" button, where the first doesn't seem to register.

**Comment by MarioCarloni** [comment]
As I am unable to reproduce the error locally, and in order to avoid the error entirely, I will need to significantly rework most of the Calibration Name form logic in a new fashion.

**Comment by cahearn** [comment]
Still finding the extra warning, though behavior was more consistent initially.  Found for existing Configs/Consts (on ADCPS-J), newly created Consts on existing Parts (on VICS) and newly created Parts.  I was always seeing these two warnings as I attempted removals. 

![image](https://user-images.githubusercontent.com/14059724/105797443-fd3a8480-5f5d-11eb-9a86-88028511b60b.png)

![image](https://user-images.githubusercontent.com/14059724/105797619-56a2b380-5f5e-11eb-8390-fff3012a4f9d.png)

After some iterations, eventually I began to find the second warning would require two clicks to clear.  Also, between warning modals, the advance to the next screen was changing, with a longer flash introduced.  Plenty of details to discuss if they seem relevant.


I then managed to get (and reproduce) this error by checking the box in the second warning, clicking ok and then canceling the removal once back to the Update Configs/Consts screen.

![image](https://user-images.githubusercontent.com/14059724/105798277-cd8c7c00-5f5f-11eb-8d01-57be2d252d32.png)

**Comment by MarioCarloni** [comment]
I am looking into additional solutionsSince standard browser warning modals are behaving inconsistently, a custom warning modal might behave more predictably in the long-run. Building an app-wide solution may be a significant enhancement, but a worthwhile one.

**Comment by cahearn** [comment]
WOW!  It's clear that you really spent time trying to solve more than just the minimum required by this request.  The new layout and interface for this bug fix represents a significant improvement that extends well beyond the needs of the tool.  The work you did to address core functionality here will benefit us across the application.  Many thanks for your hard work and KUDOS!!!

![image](https://user-images.githubusercontent.com/14059724/108015716-d7ddeb00-6fde-11eb-968e-41edf505e194.png)
