### ISSUE TITLE
Auto-delete empty CCC Events upon Removal of last remaining CCC Name from that Event

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#241]
From testing #153 (Deprecation feature):
If I Remove a CCC Name, and that is the only CCC left for an Event, that Event remains with no Names or Values showing. This empty Event should be deleted automatically. (I can at lest delete it manually for now.)

**Comment by cahearn** [comment]
This one looks good!  Tested on Staging.  Here's the event I created for CGINS-CTDBPC-50109:

![image](https://user-images.githubusercontent.com/14059724/100020720-46c7f100-2dae-11eb-9d2e-4e2723089b6a.png)


Add here's a search for the "delete_me" constant following its removal from the CTDBP-C Part Template:

![image](https://user-images.githubusercontent.com/14059724/100021093-ec7b6000-2dae-11eb-862c-0d1a17ebcfc7.png)
