### ISSUE TITLE
Add "Required" field designation

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#245]
In reference to Trello TASK 17:

**RDB-AM-050**:
RDB shall check that all required values are entered.

*Description*: Want to compare new files against similar existing files in RDB to check that all fields are filled and have required data/info

*Comment*: 

RDB does NOT currently have a concept of “required” fields, but this could be added. 

What kind of Required fields are we talking about? 
--> Make every field imported from the CSVs required with ability to manually override with a blank field, except for a select few (e.g., notes, deployedBy, recoveredBy, node.uid, orbit)
--> (Note that EA deploy CSVs are not in the same header order!!)

What action(s) should be prevented/disabled if there are missing Required fields?
--> Do required-field validation on CSV import into RDB and give a no-conformance report if not all required fields are present, and block import unless manually overriden.

**Comment by joannekoch** [comment]
Testing v1.7.0 Scenarios:

1. Set Cruises required fields for CSV Import Configuration: Ship Name, Start Date, End Date. Start with an empty Cruise database. Set the following fields to blank for the Unrecovered CUID in the Github CSV Cruise import file: shipname, cruise start, cruise stop. Upload Github CSV Cruise file. The import is Successful, no error is flagged, but no Cruises are imported. 

![Capture](https://user-images.githubusercontent.com/65416034/109983413-cd0aa200-7cd0-11eb-8f38-ad9d4ab37c08.PNG)

2. Set Cruises required fields for CSV Import Configuration: Ship Name, Start Date, End Date. Start with an empty Cruise database. Set the following fields to blank for the Unrecovered CUID in the Github CSV Cruise import file: shipname. Upload Github CSV Cruise file. The import is Successful, but no error is flagged for the Unrecovered CUID. All Cruises are imported. The ShipName for Unrecovered is blank in the Cruise database

3. Set Cruises required fields for CSV Import Configuration: Ship Name, Start Date, End Date, Notes. Start with an empty Cruise database. Upload Github CSV file. Import flags an error: File: CruiseInformation-import, Row 69: Import Config disallows blank Notes. But row 69 has a note and row 71 has a blank.

![Capture](https://user-images.githubusercontent.com/65416034/109982438-e9f2a580-7ccf-11eb-9d62-18c1a3ee5ff4.PNG)

I can supply my Cruise import file if needed.

**Comment by joannekoch** [comment]
Fixed and working nicely.
