### ISSUE TITLE
403 Forbidden Screen Displayed when Inventory User Role Selects Cruises

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#246]
"403 Forbidden Screen" is displayed when a User is logged in as an "Inventory Only" User Role and then the User selects "Cruises".

**Comment by spetillo** [comment]
At this point, an "Inventory Only" User Role should be able to view the Cruises, but not edit them.

**Comment by ethanandrews** [comment]
permissions updated
