### ISSUE TITLE
Change the "Max Calibration Coefficient decimal places" default to 15

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#247]
In short, let's change the "Max Calibration Coefficient decimal places" default to 15.

Reasoning: The "Max Calibration Coefficient decimal places" configuration is somewhat redundant at this point with the sig fig limits also set when you initialize CCC coefficients in the Templates. In addition, the "Max Calibration Coefficient decimal places" default to 0 trips people up more than necessary, and requires custom configuration for almost literally every Part Template that uses CCCs. At a minimum, the "Max Calibration Coefficient decimal places" default should be changed to something >0 that is sufficiently large that it would be somewhat ridiculous to exceed. 15 decimal places would probably be high enough in most cases, and would alert us to a CCC value import that requires more decimal places than that (suggesting that the imported value may be wrong, or at least worth double-checking).

**Comment by cahearn** [comment]
Tested on v1.6.1 on Staging.  Good to Go on this one!
