### ISSUE TITLE
For Builds, display Assembly Template name before the Build number

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#248]
For Builds, display Assembly Template name before the Build number (instead of the current display of [Build #]-[AT name]). This will make the ordering consistent with the [name]-[(serial)number] display for Inventory Parts on the Build.

**Comment by spetillo** [comment]
@ethanandrews What Milestone is this work merged into?

**Comment by cahearn** [comment]
Tested good on Staging

![image](https://user-images.githubusercontent.com/14059724/103011527-163bba00-4508-11eb-86bf-704c25aca871.png)

**Comment by ethanandrews** [comment]
@spetillo milestone 1.6.1
