### ISSUE TITLE
Do not allow duplication of Assembly Template names

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#249]
When copying an Assembly Template, an AT name the same as an existing AT should not be allowed.

**Comment by spetillo** [comment]
@ethanandrews What Milestone is this work merged into?

**Comment by cahearn** [comment]
Tested good on Staging

![image](https://user-images.githubusercontent.com/14059724/103011267-a5949d80-4507-11eb-82eb-443c0601b481.png)

**Comment by ethanandrews** [comment]
@spetillo milestone 1.6.1
