### ISSUE TITLE
Import Github Cruise.csv creates wrong Vessel Name and Designation

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#254]
When a Github Cruise.csv is imported, it creates Vessels even if they already exist. 

For example on import, the Vessel Name is set to R/V Atlantis and the Designation is blank. The Vessel Name should be Atlantis and the Designation should be R/V.

If a Vessel had already been imported with the correct Name and Designation, the Cruise import creates a new Vessel (with the wrong name and designation) even if it already exists.

<img width="393" alt="Capture" src="https://user-images.githubusercontent.com/65416034/99411225-597b8b00-28c1-11eb-9698-50bb58c8a9c9.PNG">

**Comment by ethanandrews** [comment]
There are some issues with data discrepancies in how OOI names vessels in the Vessels.csv vs. Cruises.csv. We will notify OOI again about issues and reconsider the validation process after they fix.

**Comment by spetillo** [comment]
@ethanandrews OOI is not currently planning on changing those fields in the CruiseInformation.csv unless CI specifically says we can (I'm asking and will re-post when I have an answer). I think you're recalling a different field that I had gotten OOI to fix for just one of the ships on the list.
We'll likely need to handle the discrepancy between CruiseInformation.csv & shiplist.csv Ship/Vessel Names on our side by parsing off the Vessel Designation (warning: some don't have a Vessel Designation) from the CruiseInformation.csv `ShipName` column.

Vessel Designations that we use so far: 
    R/V – Research vessel
    M/V – Merchant Vessel
    F/V – Fishing vessel
    CCGS – Canadian Coast Guard Ship
    RRS – Royal Research Ship

Until we hear back from CI on changing the CruiseInformation.csv, I am going to re-open this issue and mark it as Blocked.

**Comment by spetillo** [comment]
@ethanandrews @joannekoch
Surprisingly, everyone on the CI & Data Teams agreed with my proposal for changing the CruiseInformation.csv `ShipName` values to remove the vessel designator, making `ShipName` values the same as `Vessel Name` values. This change to CruiseInformation.csv is going through the PR review process right now, and then will undergo testing on the CI side to make sure it doesn't break their system. I will post again with a link when the updated Cruise CSV is approved and ready for you to re-test with.

**Comment by joannekoch** [comment]
That's great. Thank you.

**Comment by spetillo** [comment]
FYI @MarioCarloni @ethanandrews @joannekoch -
The Cruise CSV updates I mentioned above have been incorporated and posted to the CI GitHub CSVs.

@joannekoch Go ahead and re-test. If all is well, I think we can close this ticket out.

**Comment by joannekoch** [comment]
Tested the new  CI Cruise GitHub CSV on Release 1.6.1. Imported the new Cruise GitHub CSV, verified Vessel names were created properly, exported Cruise GitHub CSV, and verified that the import file matches the export file.
