### ISSUE TITLE
Import Multiple Github Csv files only Imports the first file

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#255]
Tried to  Import  Github Calibration, Cruise, and Vessel files on the same Upload Github CSVs screen (see attached) and only the Calibration file was imported. 

Likewise, tried to Import a Github Cruise and Vessel file on the same Upload Github CSVs screen, and only the Cruise file was imported.

<img width="389" alt="Capture" src="https://user-images.githubusercontent.com/65416034/99416365-c6455400-28c6-11eb-8ebb-c4898b776a9a.PNG">

**Comment by cahearn** [comment]
Upload appears to complete, but I still see the same behavior Joanne described.  Only the first of the listed files is uploaded.

**Comment by MarioCarloni** [comment]
Interestingly, all uploads process sequentially running local 1.6.1 code. I am testing further and working on a solution.

**Comment by MarioCarloni** [comment]
On Staging, I am able to simultaneously upload both an abridged Cruise and Vessel list, and display the edited values from their respective templates. However, on Demo, no Cruise or Vessel list is ever created, but the "Import Complete" bar is still shown. However, locally from 1.6.1 code, the files simultaneously upload and behave as-expected.

**Comment by cahearn** [comment]
All selected files successfully uploaded simultaneously.  In further testing, when errors were purposefully set in one of the files, other files properly uploaded while an error message displayed for the one flawed file.  Great work!
