### ISSUE TITLE
Add API Endpoint(s) for CI & OMS++ Integration

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#261]
Per #rdb_api Slack channel conversation, 11/17/2020, Please add API Endpoint(s) to facilitate CI Integration of RDB.

Rough Draft example provided by J. Futrelle & M. Chagnon
![image](https://user-images.githubusercontent.com/14059724/99933043-dc6c6d80-2d27-11eb-87ae-4c83373191e8.png)

**Comment by ethanandrews** [comment]
v1.6.1 has initial version of this endpoint for OMS++ to play around with

/api/v1/oms-builds/
