### ISSUE TITLE
Download CSVs from Search Screen is Broken

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#262]
Automated Testing on Rdb-testing.whoi.edu discovered Downloading CSVs from the Search screen is broken.  See attached download file. 

<img width="532" alt="Capture" src="https://user-images.githubusercontent.com/65416034/99975785-a7383d80-2d70-11eb-97d0-ba6f07512705.PNG">

**Comment by sbatchelder** [comment]
How is it that downloading csv's for #168 is working fine, but here on #262 it is not? 
Both these tickets were updated today. 

@joannekoch @cahearn What versions of the code were you both testing? If the versions are different I can start by looking at the differences. 

@joannekoch is there any way I can run your automated tests myself locally before pushing code?

**Comment by cahearn** [comment]
I was looking to test v1.6.0 functionality, which is running on Staging (ooi-cgrdb-staging.whoi.net).  I had no problems there in limited testing, specifically looking for "502 Bad Gateway" errors, and just double-checked that it's still working.

Using the same search and download steps from the Staging double-check, I also confirmed the error Joanne found on Testing (rdb-testing.whoi.edu) which is running v1.6.1.

**Comment by joannekoch** [comment]
Yes, the error is on v1.6.1 and it occurs even if you only download 1 item.

**Comment by sbatchelder** [comment]
Was able to reproduce and do a one-liner fix for this issue for v1.6.1

**Comment by joannekoch** [comment]
Verified that this fix work. Nice job! Thank you.
