### ISSUE TITLE
Bulk Export Calibrations CSV Field Errors

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#263]
The following field errors occur when Bulk Export Calibrations:

1. All Serial Numbers in the csv file are blank.

2. Some Values in the csv file are: "SheetRef:scalib2" and there is an .ext file in the downloaded zip folder. I'm not sure why there are .ext files.

**Comment by spetillo** [comment]
@joannekoch For (2), is your `scalib2` a 2D array? For 2D arrays, the expected behavior is that Values end up in the .ext files, and the .ext files are referenced using the "SheetRef:[CCC Name]" in the CSV file.

**Comment by joannekoch** [comment]
@spetillo Yes, scalib2 is a 2D array. Thanks for the info.

**Comment by sbatchelder** [comment]
@joannekoch 
re (1) 
The current behavior is to use the User Defined Field "Manufacturer Serial Number" value for the Serial column of the csv (with caveat for OPTAA instruments). If the UDF/value doesn't exist, it defaults to blank.
I think this was the desired behavior while we were focused on the CI github-csv task.

@spetillo in absense of "Manufacturer Serial Number", what should the default be? The `inventory_item.serial_number`, blank, or something else?

**Comment by joannekoch** [comment]
@sbatchelder  – I define a Manufacturer Serial Number for the Part Type associated with the Inventory I’m importing the Calibrations for.  I set the Manufacturer Serial Number to 2004 in the Inventory. 

If I upload a Calibrations.csv with a Manufacturer Serial Number of 1111, the import works and no error is thrown even thought the serial numbers do not match.

If I set the Manufacturer Serial Number to blank in the Inventory and upload a Calibrations.csv with a 1111 Manufacturer Serial Number, the blank Manufacturer Serial Number remains in the Inventory.

If I upload a Calibrations.csv with a blank Manufacturer Serial Number it works and no error is thrown.

So, what is the point of this field in the csv file? It seems to serve no purpose.

Also, this is the ONLY case in the import/export Github csv process where the import file will not match the export file.

**Comment by sbatchelder** [comment]
Well, this sounds more like an import bug than an export bug, so I'm pulling in @MarioCarloni for this.
Could this be related to #272 where imports can fail silently?

@joannekoch is there any chance you can get a log-entry/stack-trace from the CeleryWorker process for when you upload a calibration csv?

**Comment by spetillo** [comment]
@sbatchelder In absence of "Manufacturer Serial Number", default that value to blank in the export. Can you also comment out any line that has a blank in the Serial column?

**Comment by spetillo** [comment]
@joannekoch @sbatchelder @MarioCarloni I have posted the Import issues @joannekoch described [above](https://github.com/WHOIGit/ooicgsn-roundabout/issues/263#issuecomment-732958118) to #274 to keep Import issues separate from Export-specific issues.

**Comment by sbatchelder** [comment]
@spetillo 

> In absence of "Manufacturer Serial Number", default that value to blank in the export. Can you also comment out any line that has a blank in the Serial column?

What do you mean by this? Since each csv corresponds to a CCC subset of one inventory item, if that item doesn't have a "Manufacturer Serial Number" udf, then all rows will have a blank Serial column. 

This to me means: don't export CCCs for inventory items that don't have a "Manufacturer Serial Number" udf value.
Is that correct?

**Comment by spetillo** [comment]
@sbatchelder Oooh, sorry, I was thinking deployment CSVs (which have multiple instruments/Parts per file) instead of Calibration CSVs. Forget the part I said about commenting out the line. Just leave the "Serial" column blank.

**Comment by joannekoch** [comment]
@spetillo I have a question. When I look at the Asset Management csv files, they all have the serial number field filled in with something. None of them are blank. If the work flow is import a Github csv, export it, and the files should match, the files will not match if we allow a blank serial number in the export.

**Comment by sbatchelder** [comment]
Yes, and if an inventory item has a non-blank "Manufacturer Serial Number" (MSN) in the database, then that is the value used and the export "Serial" column will not be blank (see code snippet).

I was only able to recreate the error of a blank serial-column export by wiping the MSN from the inventory. The import still worked fine, since I believe it uses the filename to find the right inventory item, but the import I don't think sets or checks the MSN of an inventory item when the calibration is imported!

In conclusion,

**Comment by sbatchelder** [comment]
I just noticed that the sister-issue to this one #274 is closed/resolved.
@joannekoch does that now fix the situation with this issue?

**Comment by joannekoch** [comment]
Yes, this situation is now fixed. Thank you.
