### ISSUE TITLE
Bulk Export Vessels with Empty Active and R2R fields Exports Nothing

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#264]
If a Vessel has empty Active and R2R fields, the Vessel is not exported in the Bulk Export File.

**Comment by sbatchelder** [comment]
@joannekoch What do you mean by an empty field here? Is this via csv upload?

I tried to reproduce the error but the primary means I know of is via the Cruise > Vessel List > Add Vessel route, and that form only has Yes/No options for Active and R2R. A test where a vessel had both as "No" showed up fine in the download list. 

![image](https://user-images.githubusercontent.com/44208509/100143649-a59b7200-2e63-11eb-8832-560fc9641480.png)

**Comment by joannekoch** [comment]
Issue #210 References empty Active and R2R fields. 

Try to import https://github.com/oceanobservatories/asset-management/blob/master/vessel/shiplist.csv
The Dauntless and Matthew Hughes have empty fields in this file. When you import, these Vessels are created but they are not exported.

**Comment by sbatchelder** [comment]
Okay this is a bit dumb but where is the upload interface? I tried going to `<localhost>/ooi_ci_tools/import/vessels/upload/` which i think is the right path but that's clearly not it. Where is the upload interface accessed from?

**Comment by joannekoch** [comment]
Yea, I had to clone it to my desktop...  Here's my file. Just rename it: shiplist-import.csv.  

[shiplist-import.txt](https://github.com/WHOIGit/ooicgsn-roundabout/files/5592602/shiplist-import.txt)

**Comment by sbatchelder** [comment]
Err, what I mean is, I don't know where "bulk upload" for vessels/in-general is found on the _RDB interface_.

and fyi you can download a single file off a git repo without cloning the whole thing using the `Raw` button towards the start/top of the file :)

![image](https://user-images.githubusercontent.com/44208509/100156273-9b36a380-2e76-11eb-894d-936aed329714.png)

**Comment by joannekoch** [comment]
Click on the "Wheel" icon. Choose "Upload Github CSVs".

Thanks for the tip!

**Comment by sbatchelder** [comment]
Ah well there's the issue, I don't have the wheel/gear icon on my interface. 
Turns out my user is not Admin.
I can probably find a way to change that. Thanks!

**Comment by cahearn** [comment]
Looks Great! Tested on Staging, with repeated imports of fictitious R/V Bosun. Also, the _Dauntless_ and _Matthew Hughes_ show up in export.  Nice work!
