### ISSUE TITLE
On "Add Sub-Assembly" and "Add to Parent Assembly", searching for/scanning S/N should only return Inventory Parts available from the original list of available Inventory Parts shown

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#266]
On "Add Sub-Assembly" (and probably "Add to Parent Assembly"), searching for/scanning S/N should only return Inventory Parts available from the original *filtered* list of available Inventory Parts shown.

Currently, for "Add Sub-Assembly" at least, the original filtered list gets unfiltered when you search for/scan a S/N. So if you search for (e.g.) "35", *all* Part Inventory items in RDB that contain "35" are currently returned, instead of just the Parts with  S/N containing "35" in the original filtered list.

**Comment by sbatchelder** [comment]
@spetillo Are we talking about this page?
If so, I don't really have anything to do with this search field (which isn't to say i'm divesting myself from the task, only that I don't know much about it rn)

![image](https://user-images.githubusercontent.com/44208509/100135402-96162c00-2e57-11eb-968e-f3535f07a11a.png)

**Comment by ethanandrews** [comment]
@sbatchelder this one is on me, don't worry about it.

**Comment by ethanandrews** [comment]
Issue fixed
