### ISSUE TITLE
Enhance Comments Functionality

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#268]
In reference to Trello TASK 22:

RDB-AM-057:
RDB shall include a free text field for capturing comments associated with items in the change log.

Description: Need to be able to enter an explanation for changes to metadata.

RDB-AM-061:
RBD needs to allow “replies” to notes that are shown as sub-notes, and allow delete/edit/etc of notes.

Description: Need to be able to enter an explanation for changes to metadata.

Comment (for both): "NOT currently a function of RDB. In the current system, these would show up as new, separate comments in the Notes area.

Use notes field on the entries to add specific notes.

In addition, in general, RBD needs to allow “replies” to notes that are shown as sub-notes?-->YES, and need to be able to also delete/edit/etc."

**Comment by joannekoch** [comment]
Able to create/edit/delete/reply to a comment to change log events.
