### ISSUE TITLE
Importing Vessel CSV fails silently

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#272]
While working on #264 / #271 I noticed that the vessel csv upload task did not fully update the vessel list - it was interupted partway through.  More importantly, the upload interface did not inform the user that some error had occurred, instead showing a green "Import Complete" message, despite the import only partially working.

The error occurred because the database contained two Vessel entries bearing the same `vessel_name` value. When a vessel was queried for updating, the Celery task threw an error, halting the rest of the vessel import process. 

In my case, my database had a duplicate entry for the R/V Atlantis. Deleting the duplicate vessel resolved the error but it is possible that such a duplicate entry - or even a unique vessel entry that only happens to have the same vessel_name as some other different vessel - may happen again in production. 

Whatever the case, generally speaking, if the upload should fail partway through for any reason, the interface should inform the user. 

Below is the Celeryworker stack trace:

```
[2020-11-25 19:00:03,618: INFO/MainProcess] Received task: roundabout.ooi_ci_tools.tasks.parse_vessel_files[48a33ce1-4384-48af-8c19-64e85196110d]  
[2020-11-25 19:00:03,693: ERROR/ForkPoolWorker-4] Task roundabout.ooi_ci_tools.tasks.parse_vessel_files[48a33ce1-4384-48af-8c19-64e85196110d] raised unexpected: MultipleObjectsReturned('get() returned more than one Vessel -- it returned 2!')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/roundabout/ooi_ci_tools/tasks.py", line 307, in parse_vessel_files
    vessel_obj, created = Vessel.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
roundabout.cruises.models.Vessel.MultipleObjectsReturned: get() returned more than one Vessel -- it returned 2!
```

**Comment by cahearn** [comment]
Upload appears to be broken in a few ways.

I am having trouble uploading abridged vessel lists to any of Testing, Staging and Demo sites.  Not sure what's causing the failure to upload, may be user error, but in all cases the progress bar shows all green "Import Complete"

![image](https://user-images.githubusercontent.com/14059724/102395450-22c08f80-3fa9-11eb-8d58-611c8911d743.png)

![image](https://user-images.githubusercontent.com/14059724/102395496-353ac900-3fa9-11eb-9fcd-e2cda2133c45.png)

**Comment by MarioCarloni** [comment]
I am able to create and update an abridged Vessel CSV and its RDB equivalent from local 1.6.1 code. I will look deeper into what may be causing the issue on the live server.

**Comment by MarioCarloni** [comment]
On Staging, I am able to simultaneously upload both an abridged Cruise and Vessel list, and display the edited values from their respective templates. However, on Demo, no Cruise or Vessel list is ever created, but the "Import Complete" bar is still shown. However, locally from 1.6.1 code, the files simultaneously upload and behave as-expected.

**Comment by cahearn** [comment]
[Tested on Staging]
When testing with a file containing flawed date fields, the upload tool fails and displays an informative error message.  Great Job!

(side note: If a Cruise CSV is uploaded with a "ShipName" that doesn't match an existing RDB "Vessel Name" a new entry is created for this record in the RDB Vessel List.  This had probably contributed to the noted repeats in the Vessel list and is a feature we should re-consider)

![image](https://user-images.githubusercontent.com/14059724/103805351-73179400-5021-11eb-8c04-113b8732df9d.png)
