### ISSUE TITLE
Inventory with location Null throws error

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#276]
While working on #275 I was able to access inventory items with location `Null`.

The views for [such items](https://ooi-cgrdb-staging.whoi.net/inventory/578) do not render:

`django.urls.exceptions.NoReverseMatch: Reverse for 'locations_detail' with arguments '(None,)' not found. 1 pattern(s) tried: ['locations/(?P<pk>[0-9]+)/$']`

@spetillo @cahearn @ethanandrews 
What should the correct behavior be? Presumably rdb should show the inventory item even if has a null location, perhaps with an info/warning banner?

**Comment by ethanandrews** [comment]
I think @sbatchelder suggestion is a good fix for this issue, I will implement and close.
