### ISSUE TITLE
TASK6: Support URL links

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#284]
Create interface for adding url-links or a document-uploads (w/ description text) to various RDB models/actions, including:

- Inventory items
- top parent of a Build
- ~~top parent of an Assembly Template~~
- Vessels
- Cruises
- CCC Events

See [Trello Card](https://trello.com/c/QceB7ifK/)

**Comment by cahearn** [comment]
Awesomeness!  These look great!  Two very minor things I noticed:
1. Vessel links are the only ones that open in the working tab.  The others open in a new tab.  I prefer the "open in a new tab" option, and would choose it for the Vessel links, if that's possible.
2. For ATs, leaving the "Document Type" field unselected prevents entry from being accepted, but there's no error/feedback that this field is required.  I know the links for ATs are a legacy implementation, and don't come from your work here Sidney, but wanted to mention it here.

**Comment by cahearn** [comment]
Update addressed both of the above minor issues.  Awesome!

**Comment by cahearn** [comment]
Found new issue I hadn't noticed before:  When entering a link for Inventory items in the "Edit Details" option under the "Choose Action" menu, the url I entered is appended to https://rdb-testing.whoi.edu/inventory/ 
![image](https://user-images.githubusercontent.com/14059724/121295711-832bec00-c8bd-11eb-9945-19e61ae4686d.png)
![image](https://user-images.githubusercontent.com/14059724/121295773-99d24300-c8bd-11eb-97cd-938e75a21be0.png)
![image](https://user-images.githubusercontent.com/14059724/121295824-ace51300-c8bd-11eb-9111-324f24772c05.png)

**Comment by sbatchelder** [comment]
Good catch. This is happening because your entered url does not start with https:// or http:// 
This should be an easy fix.

**Comment by joannekoch** [comment]
Link Url for Vessels is still being appended to rdb-testing url when the link does not start with http:// or https//:

https://rdb-testing.whoi.edu/cruises/vessels/www.msn.com

In addition, Link Url for **Cruises and CCC events** does not allow a url without http:// or https://.
![Capture](https://user-images.githubusercontent.com/65416034/124819086-ca97ad80-df39-11eb-98a2-c5d1853805fd.PNG)

**Comment by joannekoch** [comment]
Urls have been fixed on vessels and inventory.
