### ISSUE TITLE
CSV Import: Generate Calibration Names, discern Coefficent Value set type

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#286]
During CSV import, auto-generate missing Calibration Names and discern their Value Set Type using respective Coefficient Values

**Comment by cahearn** [comment]
May not be testing what you're intending here but unfortunately, I'm not seeing the auto-generation for any Cal Names.  Tried to upload CGINS-PCO2WC-C0103__20141111 from Github CSVs and got attribute error page below. 

![image](https://user-images.githubusercontent.com/14059724/102739752-fd6eb100-431b-11eb-8cce-16b6cba0c99c.png)

**Comment by MarioCarloni** [comment]
This is a local bug as well. It seems to be coming from the Calibration auto-generation logic, regarding database transactions to create Calibration Names not yet found in RDB. I am currently working towards a solution.
