### ISSUE TITLE
Bulk Export "Calib with Config & Const" exports a text file

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#289]
Bulk Export option "Export Calibrations with Configurations and Constants" exports a text file (in the zip file) 
when it should export a CSV file.

[CalibrationsWithConfigs_exportlog.txt](https://github.com/WHOIGit/ooicgsn-roundabout/files/5705367/CalibrationsWithConfigs_exportlog.txt)

**Comment by sbatchelder** [comment]
Ah I misunderstood you at the meeting. 

This is not a CCC, this is a logfile of the exported CCCs. It's useful for determining why certain CCCs aren't exported.
It's useful debug information and I will make an update to remove this behavior.

**Comment by sbatchelder** [comment]
(removed a comment)

**Comment by cahearn** [comment]
I don't see .txt files in the "Export Calibrations with Configurations and Constants" zip, or any of the other Bulk Export results.  Great job!
