### ISSUE TITLE
Upload Github Cruise and Vessel CSVs Creates Duplicate Vessels

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#290]
If you upload Vessels first then upload Cruises, 2 of each Vessel Name is created IF that Vessel is in the Cruise file. The Vessel created by the Cruise upload is empty except for the name and the other Vessel created by the Vessel upload is fully populated. For Example:
       | Adolf Jensen |   |   |   |   |   |   |   |   |   |   |   |   | 
      AJ | R/V | Adolf Jensen |   | 60North | OYTL | 331185000 | 6708575 |   |   |   |   | Yes | No

If you upload Cruises first and then upload Vessels, only ONE Vessel for each Vessel Name is created.  In the case of Adolf Jensen, only the fully populated Vessel is created. The ONLY duplicate Vessel created is the Blackhawk Vessel:

  | Blackhawk |   |   |   |   |   |   |   |   |   |   |   |   | Edit Delete
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BK | M/V | Blackhawk |   | Ryan Marine |   |   |   |   |   |   |   | Yes | No

It seems the duplicate checking logic is missing mostly from the Cruise import.

The CSV files cannot be attached here, but I can send them on request.

**Comment by ethanandrews** [comment]
@joannekoch This issue should be fixed now in 1.6.1 branch. Give it a test, code is deployed to staging server as well.

**Comment by joannekoch** [comment]
Tested on 1.6.1 and there is only one Vessel per Vessel name created. Nice job!
