### ISSUE TITLE
KeyError Screen Thrown When Upload Github CSV Cruise File as a Vessel File

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#294]
Choosed Upload Github CSVs. Under Vessels Csv "Choose File" option, select a Github Cruise File and a KeyError Screen is thrown. An error message stating that the file is invalid should be displayed instead.

<img width="750" alt="Vessel Cruise Error" src="https://user-images.githubusercontent.com/65416034/103236236-59d06280-4912-11eb-84b6-9a80dec92f90.PNG">

**Comment by cahearn** [comment]
[Tested on rdb-testing]
Looks good!
![image](https://user-images.githubusercontent.com/14059724/105796631-40482800-5f5d-11eb-9c06-2f53b224f070.png)
