### ISSUE TITLE
Able to Create Build with Invalid Deployment Cycle Dates

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#300]
I'm able to Create a Build with the following cycle dates:
![deploy1](https://user-images.githubusercontent.com/65416034/104348531-d137f180-54cf-11eb-81ad-91e2195b72d8.PNG)

When I Edit Deployment Details of the Build, don't change any of the fields on the screen, and select Update the Deployment, I get the error: "Deployment Cycle dates are invalid. Check that that dates are in correct order". (extra "that" in error too).
![deploy2](https://user-images.githubusercontent.com/65416034/104348905-43103b00-54d0-11eb-8c4d-e73a23158398.PNG)

Steps to reproduce: 

1. Create a New Build
2. Add Inventory to Build
3. Start Deployment->Initiate Burnin->Deploy Build
4. Remove Inventory from Build by Selecting Recover from Deployment
5. Select greyout Inventory item from navtree and click "Add" to re add Inventory to Build.
6. Set Date Deployed to 2 days prior to current date and select "Update Inventory".

On Release 1.6.1.

**Comment by ethanandrews** [comment]
fix added in 1.7
