### ISSUE TITLE
Deleting Multiple Config/Constants & Calibrations only deletes one

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#303]
Four Configurations/Constants are defined for a Part Template.

![cc1](https://user-images.githubusercontent.com/65416034/104636848-f9f7ec80-5671-11eb-8437-dd2f029c7821.PNG)

Edit the Configurations/Constants and remove all four as shown below.

![cc2](https://user-images.githubusercontent.com/65416034/104636947-1f84f600-5672-11eb-9738-b30e4b6dc676.PNG)

Only one of the Config/Constants are removed.

![cc3](https://user-images.githubusercontent.com/65416034/104637023-388da700-5672-11eb-95e0-ead5269cc989.PNG)

Same behavior on the Edit Calibrations screen.

Behavior is repeatable on v1.6.2.

**Comment by MarioCarloni** [comment]
So far, I'm seeing similar behavior with Revision Documentation forms for Parts and Assemblies on both Staging (v1.6.2) and Demo (v1.6.1). From several Parts I'd attempted to remove individual Config/Constant Names, and Revision Documentation, but only the first item from each set was removed. Generally, there seems to be an issue with any form containing logic to generate/delete multiple form rows. These forms use a JQuery module to handle communication between the UI and Django back-end during creation/removal. I'm looking more into the core module to glean for any clues.

**Comment by cahearn** [comment]
As in #240, another fantastic improvement, resulting from deep and dedicated work.  Thanks for your efforts on this!  

![image](https://user-images.githubusercontent.com/14059724/108015919-4fac1580-6fdf-11eb-81f6-9fae4f98f90c.png)
