### ISSUE TITLE
Unclear Requirements for Export Calibrations with Configs & Constants

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#312]
When performing Bulk Download Tool -> Export Calibrations with Configurations & Constants, it is not clear what data needs to be created by the user in order for download data to appear in the zip file. 

This scenario returns data even though **_no Constants_** are defined:
1. Adds and Approves Calibrations for a Part Template.
2. Adds and Approves Calibration Coefficients for Inventory associated with the Part.

Then, if the user:
3. Adds and Approves Constants and Configs for the Part Template - no data is downloaded.

Then, if the user:
4. Adds and Approves Constants for the Inventory associated with the Part - no data is downloaded.

Only then if the user:
5. Adds and Approves Configurations for the Inventory associated with the Part - is data downloaded.

- Look into Exporting a .txt along with the bulk export files that details exactly how/why events are included/excluded in the export, it might make sense to bring that feature back because it does get quite convoluted.

- Revisit the scenarios above to make sure they make are correct. Why is data downloaded in steps 1 & 2, when no Constants are defined?

- Clarify the Download text something like:  Export Approved Calibrations with Configurations & Constants

Note: When "Export Calibrations" or "Export Configurations & Constants" is executed, data is always returned as long as calibrations and configs & constants are defined. They need not be approved to be included in the download.

Tested on v1.6.3.

**Comment by sbatchelder** [comment]
I'm adding back the export log file for CI CCC exports in my next pull request.
From what you describe above, I think the the "Export Calibration Events with Configs" is working properly.
If a part has calibrations, configurations and constants defined, they must all be present in an inventory for them to be exported. @spetillo and I worked extensively on this behavior and you can see our notes on that here: https://github.com/WHOIGit/ooicgsn-roundabout/issues/148#issuecomment-695085720

**Comment by joannekoch** [comment]
Adding the export log file back in is a good idea. I hope it will add clarity for the user.

If everything is working as designed, I guess the only issue I have is with RDB semantics.
"Export Calibrations with Configurations & Constants" implies that Configs &  Constants are defined, but
this scenario returns data even though no Configs & Constants are defined. Only Calibration Coefficients
are defined.

1. Adds and Approves Calibrations for a Part Template.
2. Adds and Approves Calibration Coefficients for Inventory associated with the Part.

**Comment by joannekoch** [comment]
Done and also fixed by issue #406.
