### ISSUE TITLE
Search User: Add "Inventory" and "Part" columns to (Misc.) Actions table

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#314]

**Comment by cahearn** [comment]
The entries in those columns should appear as links to the items, as they do in other User Search Tables.

![image](https://user-images.githubusercontent.com/14059724/106024839-2a8a4e00-6096-11eb-9330-ec973bd467b4.png)

**Comment by cahearn** [comment]
Great Update!  Though not exactly as requested, the addition of a single, linked "Associated Object" column is a much better choice for the "Actions" Search results.  Excellent work!

![image](https://user-images.githubusercontent.com/14059724/108014746-90565f80-6fdc-11eb-926f-318faee538b1.png)

[Tested on Staging]
