### ISSUE TITLE
Add the option to copy Config Defaults to new AT Revs

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#325]
Currently, the Config Defaults are not carried forward when a new AT Rev is created, which means a massive amount of work is needed to re-enter all of those Config Defaults that do not change much between Revs.

This task is to give the user the option to copy Config Defaults from a specific Rev to a new Rev, when a new AT Rev is created.

**Comment by cahearn** [comment]
Requested that optional Config Copy feature allow choice of Template Rev when creating a new Rev or when Copying a Template to a new AT.
Testing and more development addressed a couple minor details (a typo, spinning wheel when "-----" selected from dropdown, and the wrong templates referenced by the blue "New Revision" link in the "Notice" warning text box).
Optional Config Copy for New Rev and AT Copy functions looks solid and good to go for 1.6.3!
[tested on Staging]

![image](https://user-images.githubusercontent.com/14059724/108540634-6e483000-72af-11eb-92eb-5a9ccaa02867.png)
