### ISSUE TITLE
Search Actions, User results in Name Error v1.7.0

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#330]
New issue cropped up in release v1.7.0.  Occured on https://rdb-testing.whoi.edu/.

![NameError](https://user-images.githubusercontent.com/65416034/108080106-857fe700-703d-11eb-84c0-eecfb7fa9ebe.PNG)

**Comment by cahearn** [comment]
Cannot recreate.  Looks to be fixed.  Great work!
