### ISSUE TITLE
Users with "Inventory Only" included in their "User Role" are excluded from the "Reviewer" List.

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#338]
Although this is not the intended use of User Roles, in other settings we have designed users to be given access to their highest level role.  See User "dwickman" in the screenshots below:

![image](https://user-images.githubusercontent.com/14059724/109204950-f7f67280-7773-11eb-96fe-604b19092894.png)

![image](https://user-images.githubusercontent.com/14059724/109205009-09d81580-7774-11eb-8146-e62e68a34da1.png)

**Comment by joannekoch** [comment]
Able to specify Reviewer with all role assigned to the Add Configurations screen. Works!
