### ISSUE TITLE
HTML Tags displayed in "Detail" Search Results

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#341]
Steps to reproduce: 

1. Add a long Note to an Inventory Item. The Note has at least 4 lines of 44 characters. 
2. Search->Actions and Detail contains some of the characters in the Note.
3. HTML Tags appear in the Detail:

![Capture](https://user-images.githubusercontent.com/65416034/110344413-72888300-7ffb-11eb-84bb-dbc35394a2da.PNG)

Many of the "notes" and "detail" fields are saved as html strings. normally, this gets parsed and displayed correctly, but it's totally possible that the truncation happens between html tags and the html for the truncated text form doesn't correctly resolve. That might be what is happening here.

It's important to note that downloading results as CSV will always output the true html text for these fields.

**Comment by cahearn** [comment]
Still seeing the html formatting in the action search.
![image](https://user-images.githubusercontent.com/14059724/116452348-a29a1880-a82b-11eb-92df-1345c72cc6f1.png)

![image](https://user-images.githubusercontent.com/14059724/116452407-b3e32500-a82b-11eb-9a95-e4c90acefeb7.png)


Not a issue with display in standard inventory search
![image](https://user-images.githubusercontent.com/14059724/116452604-e5f48700-a82b-11eb-9164-aecbf03e1353.png)

**Comment by cahearn** [comment]
Another one bites the dust!  Nice job!
![image](https://user-images.githubusercontent.com/14059724/118023785-f3ca0200-b32b-11eb-9cf9-29c44d2fd536.png)
