### ISSUE TITLE
Disable manual row generation for Inventory CCC Events

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#342]
In reference to #208 

New Inventory-based CCC Events auto-load associated CCC Names (and Defaults). However, the functionality still exists to manually add new rows to CCC Events which results in an error. Remove row generation functionality from Inventory CCC Events, though row generation for CCC Names should remain.

**Comment by joannekoch** [comment]
Verified row generation is fixed as described above.
