### ISSUE TITLE
Filter Inventory by Part Type does not allow Navtree Expansion

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#348]
If you have an Inventory tree defined with Sewing Machine Part Types: sewing, wheel, and pin.

![Capture](https://user-images.githubusercontent.com/65416034/112040922-27529200-8b1c-11eb-9aa3-1ed8004bee7f.PNG)

Select Filter by Part Type: Sewing Machine. The drive part type is greyed out and the sewing-456-654-321 is visible as expected. You cannot expand the Singer build in the tree anymore to view the sewing, wheel, and pin (this cannot be shown with a screen capture).

![Capture1](https://user-images.githubusercontent.com/65416034/112041368-b65faa00-8b1c-11eb-8776-96da00c7047b.PNG)

If you then select Clear All or unselect Sewing Machine in the filter, you still cannot expand the Singer build.

Only if you refresh the screen can you then expand the Singer build in the navtree.

**Comment by ethanandrews** [comment]
Issue fixed in 1.7, commit cdc739d
