### ISSUE TITLE
CCC invalid behavior on v1.7.0

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#349]
New CCC bug has crept in on v1.7.0. Symptoms are different on https://rdb-testing.whoi.edu/ than on my local testing version on localhost://8000.

On localhost://8000, Calibration Coeficients can be added to an Inventory Item when a Calibration Coeficient already exists.
The same is behavior occurs for Constants and Configurations.

![Capture](https://user-images.githubusercontent.com/65416034/112876190-2fb64a00-9093-11eb-964e-69927b0a2978.PNG)

![Capture1](https://user-images.githubusercontent.com/65416034/112876194-33e26780-9093-11eb-8ad7-389c72c58c7a.PNG)

On https://rdb-testing.whoi.edu/, when I create a new Part Template "testpart" and click Create Calibrations and Create Configurations/Constants nothing happens. Also, nothing happens on Inventory Items when you try to add CCCs under the Choose Action menu.

![Capture2](https://user-images.githubusercontent.com/65416034/112879373-0bf50300-9097-11eb-82c7-3111880979f2.PNG)

**Comment by joannekoch** [comment]
I'm still seeing these issues:
On localhost://8000, "Add Calibration Coeficients" Choose Action menu item is visible for Inventory Item when a Calibration Coeficient already exists. If you fill out the Add Calibration screen and click Add, nothing gets added. The same occurs for Constants and Configurations.

On https://rdb-testing.whoi.edu/, nothing happens on Inventory Items when you try to add CCCs under the Choose Action menu.

**Comment by MarioCarloni** [comment]
Hey @joannekoch , so long as Calibration Names exist for the Inventory's Part, multiple Calibration Coefficient entries are allowed from the Inventory Action menu. As for the CCC Events not activating from the Inventory Action menu on the testing server, with which Inventory Item were you testing?

**Comment by joannekoch** [comment]
@MarioCarloni on the rdb-testing, can't add Constants to testpart 9999-2. After you select "Add Constants" fillout the form and select "Add Constants", nothing is added.

**Comment by MarioCarloni** [comment]
Interesting. For Inventory Item testpart - 9999-2, I'm able to see all the Constants you'd entered, including an additional one I'd entered. I was able to Approve and Unapprove the Constant Event, as well as Approve and Unapprove the associated Part's Config Names with a single click. Are there additional errors from your web browser's console and network tabs?

**Comment by joannekoch** [comment]
I'm seeing these console errors:


inventory_undefined
project.js:110 inventory
project.js:116 /inventory/ajax/detail/51/
jquery.min.js:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:2
project.js:156 Object
project.js:207 calibration_event
project.js:253 Object
project.js:565 Object
project.js:566 success
project.js:567 /inventory/ajax/detail/51/
project.js:583 calibration_event_18
VM13525:12 Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16/
    at Object.<anonymous> (<anonymous>:12:59)
    at E (<anonymous>:18:165)
    at Object.b [as error] (<anonymous>:11:479)
    at <anonymous>:8:230
    at <anonymous>:8:263
    at m (jquery.min.js:2)
    at Function.globalEval (jquery.min.js:2)
    at text script (jquery.min.js:2)
    at Ut (jquery.min.js:2)
    at k (jquery.min.js:2)
project.js:207 config_event}
project.js:253 Object
project.js:565 Object
project.js:566 success
project.js:567 /inventory/ajax/detail/51/
project.js:583 config_event_39
VM13525:12 Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16/
    at Object.<anonymous> (<anonymous>:12:59)
    at E (<anonymous>:18:165)
    at Object.b [as error] (<anonymous>:11:479)
    at <anonymous>:8:230
    at <anonymous>:8:263
    at m (jquery.min.js:2)
    at Function.globalEval (jquery.min.js:2)
    at text script (jquery.min.js:2)
    at Ut (jquery.min.js:2)
    at k (jquery.min.js:2)
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/atoms.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/polyfills.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/playback.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/record.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
2DevTools failed to load source map: Could not load content for http://localhost:8000/config_event%7D/highcharts.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

There are errors on the console tab for rdb-testing if you try to add a second Constant Default for testpart-9999-2.

**Comment by joannekoch** [comment]
Fixed. Able to add Multiple Calibrations, Configurations and Constants to Inventory items.
