### ISSUE TITLE
Build Review Requested flag not updated

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#351]
Steps to reproduce: Create a New Build. Start a New Deployment. Select "Edit Deployment Details" and set the Reviewers to the logged in user name. Under the Deployments tab, expand the Deployment and Select "Approve". Notice that the Current Deployment Data on the right side of the screen and the Navtree on the left side still displays, "Review Requested".

![Capture](https://user-images.githubusercontent.com/65416034/113001007-5f6e5c00-913e-11eb-8702-01d34240c9c4.PNG)

Also, when you Start a Deployment you cannot specify a Reviewer at that time. You have to Start a New Deployment and edit the Deployment Details to set the Reviewer. This is cumbersome and it would preferred to be able to set the Reviewer on the Start Deployment screen. The Reviewer is missing from the Start Deployment screen.

Tested on v1.7.0 (running on local machine).

**Comment by ethanandrews** [comment]
Bumping this to @MarioCarloni for Reviewer functionality

**Comment by joannekoch** [comment]
After following the steps to reproduce above and clicking on the Approve button, nothing happens and the deployment cannot be approved.
![Capture](https://user-images.githubusercontent.com/65416034/124763570-1cbcdc80-df02-11eb-8ab8-12325edc6a28.PNG)

**Comment by joannekoch** [comment]
This is working now. Thanks.
