### ISSUE TITLE
Total Assembly Cost is Incorrect

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#354]
For an Assembly Template, the Total Assembly Cost is zero when the cost of it's Subassembly is $56,320.00.

![Capture](https://user-images.githubusercontent.com/65416034/113150235-dae51180-9201-11eb-9f65-4ae67856bd95.PNG)

![Capture1](https://user-images.githubusercontent.com/65416034/113150252-df112f00-9201-11eb-8935-ab4a12f5c570.PNG)

Tested in v1.7.0, rdb-testing.whoi.edu &  localhost:8000.

**Comment by ethanandrews** [comment]
Cost is now specific to each Revision, shouldn't be displayed for parent Assembly. Removing line.
