### ISSUE TITLE
Download CSV for Part Templates contains bad Custom Field Default Value

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#357]
Perform Search on Part Templates. Select Download CSV. 

The Custom Field Default value for a Part Template that **does not** have the Global Field (Manufacturer Serial Number) set for that Part Type (Computerized) has the bad value: â€•

Suggest either blank or n/a for a value in this case.

![Capture](https://user-images.githubusercontent.com/65416034/113190081-ee0bd780-9229-11eb-9139-1c4b0ab26bf6.PNG)

Tested on v1.7.0.

**Comment by sbatchelder** [comment]
i'm going to go displaying `n/a` on this one. It's an easy fix :)

**Comment by joannekoch** [comment]
Great! Thanks so much! 

This value of  â€• is also showing up on the Inventory CSV for the latest calibration event date when the value is not set.

**Comment by cahearn** [comment]
Part Template CSV looks great!
![image](https://user-images.githubusercontent.com/14059724/118022608-87023800-b32a-11eb-923a-54a2e1af4b90.png)

No strange values (ie "â€•") in the Inventory CSV either, although I don't see n/a in use there.  Just blanks.  Nice work!
