### ISSUE TITLE
CCC value change recording/search/display

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#359]
CI [TASK21](https://trello.com/c/iy3y4ijt/187-task-21) [TASK23](https://trello.com/c/kpLT5s1M/189-task-23) [TASK24](https://trello.com/c/Z6hqyjrj/190-task-24)

Search CCC value changes based on reference designators.
Accessible data structure on back-end.
Convenient user-facing search and export interface on front-end.

**Comment by sbatchelder** [comment]
- Searching Inventory/Actions by Reference Designator - complete (but path to ref-des may change in the future)

- Backend data structure format needs to be formalized. Currently it is:
```
action.data = {'updated_values':{<X.name>:{'from':<X.orig_value>,'to':<X.new_value>}},
               'updated_notes': {<X.name>:{'from':<X.orig_note>, 'to':<X.new_note>}}}
```
where X denotes some ConfigValue or CoefficientValueSets. 
A TODO would be to include other changes such as approver-changes or date-changes.
This is a first-pass format and I expect it will need to be formalized. @cahearn 

- search interface as a first-pass effort exists, but needs to be re-thought. Currently the json from action.data is being parsed and displayed to something nice, but it all fits into a single cell of a table. This can be improved upon esp. if it's going to be something that should be nice to export.

**Comment by sbatchelder** [comment]
Must include a download function...

**Comment by joannekoch** [comment]
Implemented on the Search->Change screen where the Reference Designator is supplied and the CCC and Deployment Events are displayed.
