### ISSUE TITLE
Change link in Search Assembly Template Screen to be Name

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#360]
Change link in Search Assembly Template Screen to be the Name instead of Assembly Number.

The Name is a required field but the Assembly Number is not.

Go to Search->Assembly Templates. Notice that the Assembly Number is a link to the Assembly Template but in the case where the Assembly Number is not defined, there is no link. 

![Capture](https://user-images.githubusercontent.com/65416034/113302791-688e3300-92ce-11eb-8362-f03ae5ff0425.PNG)

Tested on v1.7.0.

**Comment by cahearn** [comment]
Great improvement!  Thanks for this.
![image](https://user-images.githubusercontent.com/14059724/118023286-5f5f9f80-b32b-11eb-984b-3d5db8c19743.png)
