### ISSUE TITLE
Part Type not populated when adding Top Level Part

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#364]
Navigated to a Revision of an Assembly Template. Select Choose Action->Add Top Level Part. Select a Part Template and do not select a Part Type. Click Add Sub-Assembly Part. 

![Capture](https://user-images.githubusercontent.com/65416034/114035513-28d6c680-984d-11eb-8a84-3e3e3bf9fe79.PNG)

The Part Type is not populated on the screen when a Part Template is selected above, but the outcome of the Add does know the Part Type.
![Capture1](https://user-images.githubusercontent.com/65416034/114035803-72bfac80-984d-11eb-882e-57649fe1ffc8.PNG)

**Comment by ethanandrews** [comment]
This form behaves as expected, if Part Type info is needed when a user makes a selection without using a filter, that data should be displayed somewhere else.
