### ISSUE TITLE
Current Deployment Approval badges not updating

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#365]
On Approval or Unapproval of a Deployment, if a Deployment is current, the Approval badges should update from the "Current Deployment" section of the template. They currently do not. Please resolve by allowing badges to conditionally show/hide.

**Comment by joannekoch** [comment]
On Approval or Unapproval of a Deployment, if a Deployment is current, the Approval badges are updating in the "Current Deployment" section of the template. This is working as expected.
