### ISSUE TITLE
Consolidate Part CCC Event UI/Back-end handling

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#370]
UI and back-end logic for Calibration, Configuration, and Constant Events are currently handled on a template-by-template basis. This may cause code redundancies and make features more difficult to implement in the future. Modify Event-based UI and back-end logic to generically handle existing functionality.

**Comment by joannekoch** [comment]
Mainly model and retrieval-based changes.
