### ISSUE TITLE
Part Template: Display Generated Coefficient Thresholds

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#372]
Display auto-generated coefficient thresholds from the calibration detail section of the part template

**Comment by joannekoch** [comment]
Coefficient Threshold values are zero when there are values assigned to the Coefs on the Inventory:

![Capture](https://user-images.githubusercontent.com/65416034/124780483-a378b600-df10-11eb-8c12-fcfd27ebecab.PNG)

![Capture1](https://user-images.githubusercontent.com/65416034/124780500-a70c3d00-df10-11eb-937f-36358e480c46.PNG)

**Comment by MarioCarloni** [comment]
Hey @joannekoch , what server and Inventory Item were you looking at when this occured?

**Comment by joannekoch** [comment]
@MarioCarloni localhost:8000 & Inventory sewing template that I defined in my environment. I can try to reproduce on rdb-testing if you want.

**Comment by MarioCarloni** [comment]
@joannekoch yes please! and thank you!

**Comment by joannekoch** [comment]
@MarioCarloni on rdb-testing I created calibrations sl2, test, and testcal on Part Number 4444, Test2, and the coefficients are all zero. There are Inventory Items, Test and Test2 (in Land), which have assigned coeficients for these calibrations.

**Comment by MarioCarloni** [comment]
HI @joannekoch, Thresholds are calculated with 2 or more Coefficient Values. Depending on the Coefficient Data type of the Part's Calibration, a single associated Event may not trigger a threshold update. For example, if the Part above has only one associated Event, then the Threshold update would trigger only for 2D Calibrations with 2 or more Coefficients within the Event.

**Comment by MarioCarloni** [comment]
Thanks @joannekoch.

@cahearn does this sound like required functionality? Should Calibration Names share Coefficient Threshold data across Parts, or should thresholds only be Part specific?
