### ISSUE TITLE
Inventory Action Menu Incomplete on page refresh/link

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#377]
On an inventory's detail page refresh, or when an inventory detail page is directly accessed via a link (such as from Search) the Choose Action dropdown button does not fully populate with the correct available options. 
If it is accessed via ajax however ( eg using the navtree ) the Choose Action dropdown populates correctly. 

This is reproducible on rdb-testing (v1.7.0)

**INCORRECT MENU**
===========================================================
![image](https://user-images.githubusercontent.com/44208509/115919595-0cd74580-a447-11eb-80f0-12e439612b7c.png)

**CORRECT MENU**
===========================================================
![image](https://user-images.githubusercontent.com/44208509/115919651-1d87bb80-a447-11eb-853c-516132bcfb49.png)

**Comment by joannekoch** [comment]
This seems to be fixed!
