### ISSUE TITLE
Custom Field Default Value can be set to invalid value

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#379]
It's possible to set the Default Value of Custom Field of type Dropdown to a value that is not in the Dropdown Field Option list.
![Capture](https://user-images.githubusercontent.com/65416034/116283394-d573dc00-a759-11eb-8646-be27e471bb8a.PNG)

Also, Custom Field types that are Boolean and Integer can be set to non-Boolean and non-Integer values respectively.

**Comment by cahearn** [comment]
Still seeing this.  "hello" accepted as a default for Current Status although it's not a choice in the Dropdown Field options
![image](https://user-images.githubusercontent.com/14059724/118021599-6d142580-b329-11eb-82f5-0e2af20676e0.png)

**Comment by joannekoch** [comment]
Field default value can only be set to one of the dropdown field options. Nice work!
