### ISSUE TITLE
un-Truncate long entries in search results

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#387]
Related Issue #283 
Allow for expanded text to be minimized again

**Comment by cahearn** [comment]
Not seeing this enhancement yet
![image](https://user-images.githubusercontent.com/14059724/118025274-a51d6780-b32d-11eb-833c-9e5dec1e874a.png)

**Comment by joannekoch** [comment]
I'm still not seeing this enhancement yet either. Hitting the "minus" sign does not shrink the note. Hitting the "plus" sign does nothing either. What is the definition of a very long note?

![Capture](https://user-images.githubusercontent.com/65416034/125497722-5eb79578-a239-41b9-830d-eba158ee92a1.PNG)

**Comment by sbatchelder** [comment]
Hmm, this might not be implemented in the inventory detail view. I did not realize it was a feature that ought be implemented everywhere for every note/details field.
We might have to end up spot finding/cleaning this up behavior in various places as we find them.

Here's a pic of it working in the search view on testing:

![image](https://user-images.githubusercontent.com/44208509/125504800-c5dce3ac-300d-4f05-8b13-bf21ea82d513.png)

![image](https://user-images.githubusercontent.com/44208509/125504885-d1a86410-b64d-4c56-998c-fe768c57dec4.png)

**Comment by joannekoch** [comment]
Tagging @cahearn to get his thoughts on the scope of this feature.

**Comment by cahearn** [comment]
The original scope was to provide truncation/expansion in Search results.  Long entries were making Search difficult to use.  It would be great to extend this feature throughout RDB, but that should be a new issue/card.  For this, I say we're good to go!
![image](https://user-images.githubusercontent.com/14059724/125672780-142067ed-d2b8-414e-962e-d3ce6beb6575.png)
