### ISSUE TITLE
Inventory without location

### ISSUE THREAD

**Issue by rhmunier** [WHOIGit/ooicgsn-roundabout#39]
If a location is deleted while there is inventory present there, the location for those inventory items is set to "none" and can only be found if searched for.  Attempting to view such an item causes a crash.

![NoLocError](https://user-images.githubusercontent.com/59926007/73367255-4984b300-427d-11ea-8df0-f7c9441ebb10.png)

**Comment by ethanandrews** [comment]
A fix is in place for this issue on the testing server. @rhmunier please test out the Location delete functionality

**Comment by rhmunier** [comment]
Inventory move on location deletion and validation work as intended.  Child locations are moved to top level rather than grand parent but I believe you mentioned previously that was as deliberate.
