### ISSUE TITLE
Approval functionality not working from Builds tab

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#393]
When navigating to an navtree item marked "Review Requested" from the Builds tab, Users cannot Approve or Unapprove a Deployment.

**Comment by joannekoch** [comment]
Still cannot Approve or Unapprove a Deployment on rdb-testing and local build.

**Comment by joannekoch** [comment]
Fixed. Able to approve and unapprove a Deployment. Review requested flag is updated according in the Navtree.
