### ISSUE TITLE
Onetime function to populate action history data

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#394]
DB objects created before action history data functionality do not have action history data.
Create a one-time function to be run against database to set data for objects that need action history data for display purposes.
-Sidney

**Comment by cahearn** [comment]
All looks good with a bunch of spot-checking on `rdb-testing.whoi.edu` however I don't have a known example to check for proper updating from the function run.

**Comment by joannekoch** [comment]
Spot-checking has passed and issue is resolved.
