### ISSUE TITLE
Download Calibrations CSV file missing Calibration Values

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#401]
"Search->Calibrations". Select "Download CSV" to download all. Calibration values are missing from csv file. 
Similarly search for 1 item, "Search->Calibrations AND Inventory:SN Contains 20001" and download. Calibration values are missing from csv file.

![Capture](https://user-images.githubusercontent.com/65416034/119388102-d7b55180-bc97-11eb-92f1-4ad087bdbee0.PNG)

Tested on v1.7.0

**Comment by sbatchelder** [comment]
I think that is beyond the scope of the search download functionality. 
Calibrations can be dowloaded from the Bulk Download page.
If you want a feature to download individual calibration events, then that would be an enhancement.

@cahearn what do you think?

![image](https://user-images.githubusercontent.com/44208509/119389387-8d34d480-bc99-11eb-9fe1-d4d749d76e84.png)

**Comment by cahearn** [comment]
I agree that returning the actual calibration values wasn't part of the original request for Search.  However, as users have taken up these tools I've gotten feedback that it would probably be useful, and in some cases leaves them confused as they expect the values to be there.  @sbatchelder would you please take a look at this, and other places where we aren't returning similar types of search data, and try to estimate the effort required to include them.

**Comment by sbatchelder** [comment]
Yes! I just moved it.
