### ISSUE TITLE
Unable to Approve 2 Approvers to Constants and Configs

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#403]
Steps to reproduce:

1. Login in as technical user, techy.
2. Approve Configurations/Constants on a Part Template. Approval flag is set for techy user.
3. Logout.
4. Login in as admin user.
5. Note that the Approval flag is not set for technical user anymore.
![Capture](https://user-images.githubusercontent.com/65416034/119670035-8d9eae00-be06-11eb-8588-d3a3eca8aa46.PNG)
6. Approve Configurations/Constants on a Part Template. Approval flag is set for admin user only.
![Capture](https://user-images.githubusercontent.com/65416034/119670399-dce4de80-be06-11eb-96ad-ed9605cc66ad.PNG)

There is no way to have 2 users approve at the same time which is a requirement related to issue #402.
This same behavior also occurs while trying to approve Constants/Configs on an Inventory item.

I can however approve 2 users for Calibrations - that is working fine.

Tested on v1.7.0.

**Comment by joannekoch** [comment]
Logged in as admin, tested and found:
I have to click the "Approve" button twice to get admin to be approved (when tech is already approved). Should not have to click the button twice.
![Capture](https://user-images.githubusercontent.com/65416034/124761884-4248e680-df00-11eb-8af4-f5b58fc1fd29.PNG)

Then if I select another Part Template in the navtree and then select the Part Template I had just approved and open the Config & Constants link to open the detail, the Approval for admin goes away.
![Capture1](https://user-images.githubusercontent.com/65416034/124762002-67d5f000-df00-11eb-857a-d0191b016f4d.PNG)

**Comment by MarioCarloni** [comment]
Hey @joannekoch , for the above bug, which server were you testing on, and with which Part were you testing?

**Comment by joannekoch** [comment]
@MarioCarloni localhost:8000 and any and all Parts that I create. I can also re-create it on rdb-testing with Part Template, testpart.

**Comment by MarioCarloni** [comment]
Per discussion from #349 , I'm seeing different behavior. What browser are you running? Do you see any errors in the web browser's console or network tab?

**Comment by joannekoch** [comment]
I'm running with chrome browser. I see these errors in the console tab:

Autofocus processing was blocked because a document's URL has a fragment '#issuecomment-876583738'.
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/atoms.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/polyfills.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/playback.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/record.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

With the pull request #421 today, I'm seeing this.

Steps:
1. approve Constant History event as admin - have to select it twice.
2. login in as Tech user.
3. Notice that admin is no longer an approver.
4. Select "Approve" and now an additional "tech" user is added to the review list.

![Capture](https://user-images.githubusercontent.com/65416034/124963399-c0cf8200-dfed-11eb-8cdb-61e88d2b0b44.PNG)

5. Select "Approve" again and still only the "tech" user is an approver.

![Capture1](https://user-images.githubusercontent.com/65416034/124963412-c4fb9f80-dfed-11eb-9c9c-e55603d9c8f3.PNG)

6. Sign in as admin and now no one is an approver.

![Capture](https://user-images.githubusercontent.com/65416034/124963889-5b2fc580-dfee-11eb-9d84-004135efe652.PNG)

**Comment by joannekoch** [comment]
Fixed. Able to approve CCCa on Parts, Assemblies and Inventory for both admin and tech users.
