### ISSUE TITLE
Reference Designators: Display relevant information alongside Designator name

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#411]
From the Assembly Part template, alongside the Reference Designator name, please provide the Assembly Part name, Revision number, Build name, and current Deployment.

**Comment by joannekoch** [comment]
Required information is displayed alongside the Reference Designator as shown below.

![Capture](https://user-images.githubusercontent.com/65416034/125328645-8ed25e80-e312-11eb-80ee-dbbdeaa5b83a.PNG)
