### ISSUE TITLE
"Upload GitHub CSVs" Tool is Broken

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#414]
Individual file uploads of Calibration, Cruise and Vessel CSVs show confirmation of successful completion but fail to create or update associated records.
![image](https://user-images.githubusercontent.com/14059724/122276169-8113ef80-ceb2-11eb-9c5b-5ef22821ad84.png)

![image](https://user-images.githubusercontent.com/14059724/122276223-938e2900-ceb2-11eb-8541-64b88ec931fa.png)

![image](https://user-images.githubusercontent.com/14059724/122276384-bb7d8c80-ceb2-11eb-9b90-be09171706e5.png)

![image](https://user-images.githubusercontent.com/14059724/122276534-e071ff80-ceb2-11eb-81ea-59ff9fdc8c81.png)

![image](https://user-images.githubusercontent.com/14059724/122276584-ee278500-ceb2-11eb-9dc2-41a35907d700.png)

**Comment by MarioCarloni** [comment]
Note: Per Wednesday's discussion, this may be related to an issue regarding Dev and Test Celery containers sharing cached data.
