### ISSUE TITLE
Added Calibrations not updated in Inventory Coefficients

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#426]
Steps to reproduce on rdb-testing.:
1. Create 2 Calibrations for a Part Template (3333) - test and testcal.
2. Create Calibration Coefficients and assign values on the associated Inventory (Test-3333-200002).
3. Add a new Calibration for the Part Template - sl2.

![Capture](https://user-images.githubusercontent.com/65416034/126178723-4c779a1a-6587-41e1-9928-660d717c33d4.PNG)

4. Open the Calibration Coefficient History tab for the Inventory and notice that sl2 is not added.

![Capture1](https://user-images.githubusercontent.com/65416034/126178842-254857bd-82bf-4ef1-9420-0dad2f83409d.PNG)

If the intent is not to be able to add Coefficients after they have been created on an Inventory, then the user should not be able to add a Calibration to a Part Template after the Coefficients have been created and an error message should be displayed.

**Comment by MarioCarloni** [comment]
Hey @joannekoch at some point we changed how CCC Events work so that only newly-created CCC Events (post-creation of a new Calibration Name from the Part template) will receive the new Name as an extra row. Whereas existing CCC Events can edit only their existing Names and rows.

**Comment by joannekoch** [comment]
Hi @MarioCarloni - thanks for the explanation. So this issue can be closed?

**Comment by MarioCarloni** [comment]
I believe so, go ahead!
________________________________
