### ISSUE TITLE
Comments: Show all 

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#439]
While Comments are now nested appropriately, it is difficult to discern whether or not a Comment has Replies. Expanding Comment sections by default should allow Users to not miss any relevant Replies.

**Comment by joannekoch** [comment]
When opening a detail screen, the nested comments are expanded by default as shown below. Nice work!
![Capture](https://user-images.githubusercontent.com/65416034/135318588-44fa0bcd-c468-4560-b286-ed837d70f888.PNG)
