### ISSUE TITLE
Vessel CSV Upload Silently Fails

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#442]
Vessel csv upload silently fails if `ICES Code` field of the csv is longer than 4 characters. 
The page claims that the upload finished successfully, but the celery log shows an error and the vessel entry does not get added to the database.
```
celeryworker_1  | [2021-08-25 14:18:34,030: INFO/MainProcess] Received task: roundabout.ooi_ci_tools.tasks.parse_vessel_files[db926060-46fa-4aba-9982-e3f6b375726d]  
postgres_1      | 2021-08-25 14:18:34.082 UTC [148] ERROR:  value too long for type character varying(4)
postgres_1      | 2021-08-25 14:18:34.082 UTC [148] STATEMENT:  INSERT INTO "cruises_vessel" ("prefix", "vessel_designation", "vessel_name", "ICES_code", "operator", "call_sign", "MMSI_number", "IMO_number", "length", "max_speed", "max_draft", "designation", "active", "R2R", "notes") 
                                                                VALUES ('AJ', 'R/V', 'Adolf Jensen', '12345', '60North', 'OYTL', 331185000, 6708575, '99.0', '99.0', '99.0', '99', true, false, '') 
                                                                RETURNING "cruises_vessel"."id"
celeryworker_1  | [2021-08-25 14:18:34,114: ERROR/ForkPoolWorker-4] Task roundabout.ooi_ci_tools.tasks.parse_vessel_files[db926060-46fa-4aba-9982-e3f6b375726d] 
                                                                    raised unexpected: DataError('value too long for type character varying(4)\n')
```

**Comment by joannekoch** [comment]
The ICES Code field of the csv is longer than 4 characters import problem is fixed. 

However, in testing I inadvertently set the ICES Code to a blank character (space) and the result of the import was successful, but no vessels were imported.

**Comment by MarioCarloni** [comment]
Hey @joannekoch, technically blank ICES_codes are allowed from the Cruises model. The only exception to blank ICES_codes would be if the require_ICES_code attribute were enabled from the Import Config, which should disallow blank values of whichever attributes are selected.

**Comment by joannekoch** [comment]
@MarioCarloni, I forgot to mention that I did have the require_ICES_code enabled and when the ICES code was a blank, the import was successful, but no vessels were imported.

**Comment by joannekoch** [comment]
Invalid ICES codes are properly flagged as errors. This issue is fixed.
