### ISSUE TITLE
For Deployment CSV Imports, Add Logic for Determining Proper Assembly Template Revision per Deployment

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#447]
Deployment CSVs cover the entire history of deployments for a single platform (for RDB purposes, effectively a single Assembly Template).  For RDB tracking purposes, however, it's necessary to know what version of the Assembly Template should be referenced by each deployment.

We requested the addition of the "assembly_template_revision" column to the Deployment CSVs.  Now, logic needs to be added to the Deployment CSV Import to determine the proper AT Rev from the "assembly_template_revision" value when creating the Build for each Deployment within the CSV history.

**Comment by joannekoch** [comment]
Upload the following deployment csv with the assembly_template_revision set to "B":
![Capture](https://user-images.githubusercontent.com/65416034/156399818-30934340-30c4-416b-9c78-9cf136d7a14d.PNG)

The build was not created on the Assembly Template "B". Only the revision "A" build was created previously when the assembly_template_revision was set to "blank".
![Capture1](https://user-images.githubusercontent.com/65416034/156400041-c5afaed1-7b4f-4b19-b225-83a4f539db53.PNG)

![Capture2](https://user-images.githubusercontent.com/65416034/156400170-e767e59b-3da5-463f-9205-bea736f0f949.PNG)

The 2 builds below are both on GS Surface Mooring | Revision: A 

![Capture3](https://user-images.githubusercontent.com/65416034/156400753-fbb46f20-d6e2-4283-a335-4c69af47a788.PNG)

No build was created for GS Surface Mooring | Revision: B.

**Comment by joannekoch** [comment]
Deployment 000115 was uploaded as described above and it is still on Rev A when it should be on Rev B.
![Capture](https://user-images.githubusercontent.com/65416034/158635573-f4aec0d6-3859-4d20-bc34-1eb4c4ab647b.PNG)

**Comment by joannekoch** [comment]
@MarioCarloni, I'm still getting the exact same outcome as described above.

**Comment by joannekoch** [comment]
Hey @MarioCarloni, this screen looks better and shows the two Assembly Template Revisions
![Capture](https://user-images.githubusercontent.com/65416034/165162773-e300b7f4-eb04-427f-b116-c67791391ba5.PNG)

But the Build should be on Assembly Template B and not A.

![Capture](https://user-images.githubusercontent.com/65416034/165163016-ac4402a9-4f87-4044-a6f3-96c977f34815.PNG)

This Build is on A as it should be.

![Capture](https://user-images.githubusercontent.com/65416034/165163184-4a212609-da3a-4f3e-acfe-e8a5128464ab.PNG)

Note that the Build (Historical 00011) on Assembly Rev A was uploaded previously from this upload file with a blank assembly_template_revision. The Build (Historical 000115) was created from the uploaded file shown in the March 2 comment screen above.

![Capture](https://user-images.githubusercontent.com/65416034/165164082-056641d9-3584-4544-8219-b917e6889d67.PNG)

**Comment by joannekoch** [comment]
Working. The Build was uploaded to Assembly Revison B as shown below.

![Capture](https://user-images.githubusercontent.com/65416034/170131945-a2cf40e0-41f3-4fa6-b408-cf0ca9bd8d5a.PNG)
