### ISSUE TITLE
User Request!:  Please Delete Mistakenly Entered Note

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#448]
Please delete the note on Production from 7/27/21 for Inventory Item - PSC 2.0 S/N 3709-02001-00000-20003

https://ooi-rdb.whoi.edu/inventory/126

Slack Request from K. Politano, for reference:
Kristin Politano  11:52
Okay. If it's not too much trouble, I would like to have something deleted. We're having a lot of PSC issues and I want things to be very clear when refurb time comes around.
https://ooi-rdb.whoi.edu/inventory/126 
On this inventory item (PSC 2.0 SN20003), I accidentally deployed it on CE09 when it should really be on CE04. I'm not worried about it being on the wrong mooring, I can make a new note about how I messed that up, but I want the note about the CVT failure out of there (the one below). That's an entirely different issues and it goes with a different PSC. If the thing gets refurbed for a CVT issue it won't fix the problem. 

[Text of Note to be Deleted]
7/27/21 22:11NotePossible CVT failure. CPM3 was powering on normally, but then rebooting and coming fully online 11 minutes past its scheduled on time. This caused MFN data gaps for several weeks. The reboot did not appear to be due to any CVT overcurrent/power issues, 400v was being supplied to the MFN, CPM3 was just not powering normally. After several weeks however supplied power dropped to 200v, hinting at a possible CVT failure. MFN was turned off to prevent further damage.

![image](https://user-images.githubusercontent.com/14059724/131554558-bed0ae22-642b-4b36-9093-e5e1b2578c5d.png)

**Comment by cahearn** [comment]
@ethanandrews Please take a look at this!!!

**Comment by ethanandrews** [comment]
Note has been deleted.
