### ISSUE TITLE
User Request: Please Test OneDrive Links for Compatibility

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#456]
The OBS group is considering moving some of their documentation to OneDrive and want to know how well it will work with RDB.  They currently have a lot of docs stored in a networked shared drive within the WHOI intranet, an implementation we have previously been unable to support links to.
Please give a thorough testing to a wide variety of possible uses of OneDrive links.  Many thanks!

**Comment by joannekoch** [comment]
Tested OneDrive, Sharepoint, and Google Drive links on the following RDB screens: Inventory, Build, Cruise Vessels, and Calibrations.  After entering and saving the link when clicking on the link, a new tab is opened in the browser. If the user is not logged into the drive, a login screen is presented. After the user logs in, the link to the document is opened in the new tab. 
These links work the same as any other url links.

Here are sample screen shots. The link has been saved shown by the red arrow below.

![Capture](https://user-images.githubusercontent.com/65416034/135273150-2560186e-27d3-4bfe-9a07-789e02e56e6a.PNG)
Login screen for the Drive
![Capture1](https://user-images.githubusercontent.com/65416034/135272573-6937d2ba-d0bb-401f-ac83-3673a6295d4b.PNG)
File on the Drive is opened
![Capture2](https://user-images.githubusercontent.com/65416034/135272605-621330bc-6f17-4400-8f59-eeb0dcd62f92.PNG)

**Comment by cahearn** [comment]
Fantastic!  Thanks for digging into this.  Passed on the good word and the OBS folks appreciated the news!
