### ISSUE TITLE
Bulk Upload file parsing error

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#465]
Bulk Upload imports display a Completed badge, however no data is associated with relevant Inventory or Part items. In Sentry, a generic "parse_bulk_files" error is generated. Please fix so that Bulk Upload data is effectively generated.

**Comment by joannekoch** [comment]
Bulk Upload imports display a Completed badge, and data is associated with relevant Inventory Items. This is fixed.

As an aside, I don't see any builk upload data associated with a Part as stated in the descripion above.
