### ISSUE TITLE
Bulk Upload Event History: "Calibation CSV Uploaded" Action exists

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#468]
When a Bulk Upload Event is associated with an Inventory item, an Action History item is created, whose details are correct, with the exception of the Action attribute, regarding a Calibration upload. Please resolve so that the correct Event type is shown.

**Comment by joannekoch** [comment]
The action attribute associated with a Calibration upload associated with an Inventory item looks correct to me.
![Capture](https://user-images.githubusercontent.com/65416034/153426383-4712cba0-1c23-4fa3-bbb2-9e56c2dc2c00.PNG)
