### ISSUE TITLE
Inventory Bulk Upload: "Review Requested" badge shown when no Reviewers selected

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#469]
From the Inventory NavTree, any item with an associated Bulk Upload Event is rendered with a "Review Requested" badge, even when no Reviewers were selected during import. Please fix so that the badge appears only when the Logged-In User is within a Bulk Upload Event's Reviewers list.

**Comment by joannekoch** [comment]
The "Review Requested" Badge does not appear when no reviewers were selected during an Bulk Upload import . This is working as expected.
