### ISSUE TITLE
Inventory Bulk Upload Events: File sections do not collapse

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#474]
While Inventory Bulk Upload File sections are expanded by default, they should collapse on-click of the collapse button adjacent to the Filename. However, nothing happens on-click of the expand/collapse buttons. Please fix so that the buttons toggle the display of each Bulk Upload File section.

![image](https://user-images.githubusercontent.com/5469058/142262952-e5f93ede-5ed9-4f29-89db-164886cd7503.png)

**Comment by joannekoch** [comment]
The collapse/expand toggle buttons are working.
