### ISSUE TITLE
Inventory: Add Review badges to CCCEvent-based nav-link tabs

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#478]
If an Inventory item contains multiple CCC-Event types, and a logged-in User is a Reviewer in at least 1 Event type, it is difficult to discern from the general Inventory detail template from which Event the User is a Reviewer. There is no visual indication of which context the User should look for their Reviewable Event. Provide an indication from the Inventory details template, which guides the User to their Reviewable Event(s).

**Comment by joannekoch** [comment]
The Review Requested badges are shown clearly for each event type that requires a review. Nice job!

![Capture](https://user-images.githubusercontent.com/65416034/148114915-0fe0a6e7-3708-4cee-936f-012f5667dd53.PNG)
