### ISSUE TITLE
Comments: Add new comment badges to Inventory navtree items

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#479]
There is currently no indication of when a User replies to another User via Comments. Add badges to Inventory navtree items to indicate when Comments, belonging to the logged-in User, have new child Comments.

**Comment by joannekoch** [comment]
Reply Badges have been added to Inventory navtree items to indicate when Comments, belonging to the logged-in User, have new child Comments.

![Capture](https://user-images.githubusercontent.com/65416034/152221357-e25a104d-80cc-4201-ac81-2df52369a381.PNG)
