### ISSUE TITLE
Inventory: Event tab Review badges remain post-Approval

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#488]
On-Approval of an Event, if no remaining Events need to be approved for an Event type, the Review badge for the Event type's tab should disappear. However, the badge remains post-Approval. Please fix so that the Review badge is removed during appropriate circumstances.

**Comment by joannekoch** [comment]
Approve button for events seems to be broken. When I try to approve calibrations, configs, constant defaults, reference designators, etc - nothing happens. Repeatable on rdb-testing.whoi.edu & local build.


![Capture](https://user-images.githubusercontent.com/65416034/148111261-43b4a4d7-464e-4823-96d0-aaf21f28d713.PNG)

**Comment by joannekoch** [comment]
Review badges are added and removed for all CCC events on Parts, Assemblies, and Inventory Items and working as expected.

However, I found **one scenario where the review badges are NOT** working. That is when an Inventory is added to a Build, and then that Inventory is Recovered from a Deployment. Recovering an Inventory from a Build seems to break the Review Badge addition and removal.  If the Inventory is re Deployed to the build, the review badges are still broken.

As you can see below, the Review Badge for ADCPS-J is missing after ADCPS-J was removed from the testassm build.
Before ADCPS-J was removed from the build, the badges were working as expected.

![Capture](https://user-images.githubusercontent.com/65416034/150003385-7a56f673-194e-4954-91f6-4c6cc62ce63e.PNG)

**Comment by joannekoch** [comment]
When an Inventory is added to a Build and then that Inventory is Recovered from a Deployment, try to approve ccc events on the Inventory. Recovering an Inventory from a Build used to break the review badges, but testing has revealed that this has been fixed. The user is able to approve/unapprove all review badges on the recovered Inventory. Thanks for fixing this intricate scenario of events!
