### ISSUE TITLE
Unable to Approve Bulk Upload File 

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#489]
After Bulk Upload Files are imported and a Reviewer is chosen, the Reviewer, Records and Event History are shown below in the Inventory Item.

When logged in as "admin" and the "Approve" button is selected, there's an internal server error and nothing happens.

 

![Capture](https://user-images.githubusercontent.com/65416034/145092802-7a9aee1e-36fb-4115-807c-fdf693fd47b1.PNG)

**Comment by MarioCarloni** [comment]
Hi @joannekoch , thanks for chasing this down. On-click of the Approve button, errors should be thrown from the Docker terminal as well, my guess from the Django container. Do you see any container-based errors from your local terminal?

**Comment by joannekoch** [comment]
Hi @MarioCarloni , I'm not seeing that error anymore. But, I am seeing different behavior:

When I upload a bulk csv and choose "admin" as a reviewer, there is no reviewer assigned for the bulk load event.
![Capture1](https://user-images.githubusercontent.com/65416034/146990629-f461345f-58cf-4633-8bc0-4f78503cf55c.PNG)

![Capture](https://user-images.githubusercontent.com/65416034/146990297-1faf8197-b372-4145-aee9-81ee35c5f9c2.PNG)

When I edit the bulk load event record and assign "admin" as a reviewer, the review requested process works as expected.

**Comment by MarioCarloni** [comment]
Ah, I see what's happening. This is related to #493 regarding the CSV Import Reviewer selection field. There is currently a PR to resolve #493, which, once merged, should resolve this issue as well.

**Comment by joannekoch** [comment]
When I approve the Bulk Upload Event, an Internal Server Error is thrown and the event is not approved. The django error is below.

![Capture](https://user-images.githubusercontent.com/65416034/149208232-d51ab5dd-f816-4e74-bc8b-7f1081f03bc9.PNG)
![Capture1](https://user-images.githubusercontent.com/65416034/149208874-ae19361f-d728-49b1-b01c-0345cc66c335.PNG)

**Comment by joannekoch** [comment]
After Bulk Upload Files are imported and a Reviewer is chosen, the Reviewer is able to approve the Bulk Upload Files on Parts, Assemblies, and Inventory.
