### ISSUE TITLE
Inventory: Action History: Add Comment Reply badges to parent Action History item

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#491]
Reply badges can be found for Inventory Navtree items. However, when visiting any Inventory detail page, there is no indication of which Action History, which a User has Commented on, contains replies to the User's comments. Please provide a badge to indicate that Replies to a User's Comment can be found within their respective parent Action History item.

**Comment by joannekoch** [comment]
I don't see any reply badges on the Inventory Item when logged in as either admin or tech user. Is there something missing?
![Capture](https://user-images.githubusercontent.com/65416034/148114283-02d46b70-a79d-4fbf-b66c-3f952f13798c.PNG)

**Comment by MarioCarloni** [comment]
Hi @joannekoch , the original enhancement was to add "Replies" badges to only parent, top-level Action History items, but not to the children Comments below, Are Reply badges appearing on relevant parent Action History items?

**Comment by joannekoch** [comment]
@MarioCarloni, no I still don't see any on the top-level parent, sewing.  

![Capture](https://user-images.githubusercontent.com/65416034/148612205-d0ad36dc-ded5-461c-9967-80ee4639fac7.PNG)

**Comment by MarioCarloni** [comment]
@joannekoch do you notice if either the Navtree or Action Reply badges appear/disappear when hard-reloading an inventory page vs clicking on an inventory navtree item?

**Comment by joannekoch** [comment]
@MarioCarloni - I see it on the Inventory item (circled below) that is not on a build, but I don't see it on the Inventory item that is on a build that I referenced above (see above screen shot). 

![Capture](https://user-images.githubusercontent.com/65416034/148841659-b6259529-dd77-4e62-b98c-9b3b543ca003.PNG)

**Comment by joannekoch** [comment]
Reply Badges are working on all Inventory Items, those on a build and those not on a build, as expected. Nice work!

![Capture](https://user-images.githubusercontent.com/65416034/152218439-a23960d0-f206-44e8-9135-859c0a8def0a.PNG)
