### ISSUE TITLE
Bulk Upload: Parts: Associate Vocab CSVs with Parts via Custom Fields

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#496]
When parsing a Bulk Vocab CSV, if a row's Manufacturer and Model values match a Part's Manufacturer and Model (Custom Field) values, then associate the Bulk Upload Event with the matching Part.

**Comment by joannekoch** [comment]
The sensor_vocab.csv file is the only sensor file that contains the Model and Manufacturer for this Part. Yet the platform, node, and eng sensor csv files also appear in the list for this part. Is this the intent?

![Capture](https://user-images.githubusercontent.com/65416034/149216789-07965d64-0231-4f55-9bf4-565904e9e0b6.PNG)

**Comment by joannekoch** [comment]
I would like to add that the sensor, platform, node, eng vocab files were all uploaded together in the same Bulk Upload Csv Import action.

**Comment by joannekoch** [comment]
@cahearn - Please comment on the desired behavior here and how we would like to proceed.

**Comment by cahearn** [comment]
The purpose of this card is OBE with the addition of an "RDB_Part_Template" column to the Bulk CSVs.

The issue Joanne has highlighted, however, is separate from this specific import function and should have its own card.  I'll check to make sure we haven't captured it somewhere else before creating a new issue.

**Comment by joannekoch** [comment]
Closing this issue and creating a new card for the issue dated Jan 12 above.
