### ISSUE TITLE
Part: Bulk Upload Files: File sections do not collapse

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#497]
While Part Bulk Upload File sections are expanded by default, they should collapse on-click of the collapse button adjacent to the Filename. However, nothing happens on-click of the expand/collapse buttons. Please fix so that the buttons toggle the display of each Bulk Upload File section.

**Comment by joannekoch** [comment]
The collapse/expand buttons are working as expected. Nice work!

![Capture](https://user-images.githubusercontent.com/65416034/149210021-4314747d-5cae-401e-b270-f68b3055cd43.PNG)
