### ISSUE TITLE
Assembly type validation

### ISSUE THREAD

**Issue by rhmunier** [WHOIGit/ooicgsn-roundabout#50]
The assembly type field is not a required field.  If an assembly is created with no type it can only be edited by manually entering it's information page address but still have builds created from it.

**Comment by ethanandrews** [comment]
Fixed by 832164a64bc4020b162170c571a11e646a53e8af

**Comment by rhmunier** [comment]
In testing the issue, things seem to have gotten worse.  A build can still be created without an assembly template and the list will not load (assuming java error) again but additionally the assembly information page can no longer be accessed by manually entering the address

https://rdb-testing.whoi.edu/builds/18/

![image](https://user-images.githubusercontent.com/59926007/75553194-e4e87f80-5a05-11ea-9f76-e06bc96c51e9.png)

**Comment by ethanandrews** [comment]
The fix for this has not been pushed to the testing server yet, it’s part of a larger commit that will go up soon. So no need to worry about this right now.

**Comment by rhmunier** [comment]
I was looking at the wrong issue as I apparently didn't name them distinctly enough.  What I posted earlier today was for creating a build without an assembly template (#51), not an assembly without a type
