### ISSUE TITLE
Upload Github Deployment CSV has wrong Location

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#516]
When a Github Deployment CSV is Uploaded, it's uploaded as Retired (the most recent event) and the Build is located in the "Retired" Location in the navtree.  But, the Deployment History for this location when expanded shows the Deployment Location as "Coastal Pioneer" when it should be "Retired".  In addition, the latest event shows the Location as Coastal Pioneer when it should be Retired.
See circled items below.

![Capture](https://user-images.githubusercontent.com/65416034/152866115-3ffd0697-740d-4985-8ad2-b81d62c1588f.PNG)

Regardless of the Build End Date, even in the future and actively deployed to the field, all the Builds I upload seem to end up in the "Retired" Location. See screen shot below.

![Capture1](https://user-images.githubusercontent.com/65416034/152867670-9c5f8ef4-c5cd-4425-a106-8752dee55c12.PNG)

**Comment by joannekoch** [comment]
With a Build end date in the future, the uploaded Build is still ending up in the "Retired" location as shown in the screen shot above. 

Note that prior to the upload Deployment csv file, I wiped my database clean, created the location, cruise, part, and assembly required for the upload, and the Build was still created in the Retired Location.

**Comment by MarioCarloni** [comment]
Hey @joannekoch, the Build's Location is set to "Retired" if a matching CSV row contains a "stopDateTime" value. Otherwise, the Location is obtained using the first 2 characters from the matching row's "Reference Designator" value, representing the "Location Code" for a given Location.

Please let me know if your tests are concluding otherwise!

**Comment by joannekoch** [comment]
Hi @MarioCarloni, thanks for the info regarding the stopDateTime!

When I blank out the stopDateTime (and clear any spaces), I get this error:

![Capture](https://user-images.githubusercontent.com/65416034/157509370-7b2adeb0-f211-47ec-a22c-3e70daabd4f5.PNG)

This is the file I am uploading:
![Capture1](https://user-images.githubusercontent.com/65416034/157509397-9e589198-e277-4aa0-b502-41b4d56bdc48.PNG)

**Comment by joannekoch** [comment]
When the stopDateTime is blank, the error no longer presents and the deployment is created in the location defined by the reference designator.
