### ISSUE TITLE
CCC Event: Prototype Vessel Event

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#520]
Prototype new Vessel Event model based on the CCCEvent type. Link Existing Vessel objects with new Event model.

**Comment by joannekoch** [comment]
Vessel objects are now displayed in the new event model
![Capture](https://user-images.githubusercontent.com/65416034/158628662-e0f4b24e-3324-410f-9f8c-2c7dc30e774c.PNG)
.
