### ISSUE TITLE
Calibration CSV Upload Fails for Large Values Outside of Unwanted Threshold Check

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#522]
CI-Testers found a bug in upload of certain Cal CSVs (ex: SPIKRB, DOSTAM, CTDGVM).  Upload fails for having Cal Coeffs that are too large when compared to inadvertent threshold value checks.  Not wanted at this stage as threshold checking has otherwise been disabled.  This is additionally important because it prevents even the first automated creations of Cal Coeffs Names, and thus no threshold values can be adjusted to allow for the upload to pass.  Error examples below:

`File: CGINS-SPKIRB-00248__20191210.csv, Calibration Name: CC_offset, Row: 1, Column: 1, 2147581997.2 Coefficient value falls outside of threshold (-1000000000.0,1000000000.0)`

`File: CGINS-DOSTAM-00404__20181022.csv, Calibration Name: CC_calibration_date, Row: 1, Column: 1, 1540166400000 Coefficient value falls outside of threshold (-1000000000.0,1000000000.0)`

**Comment by joannekoch** [comment]
Able to upload a Calibration Coef values in the trillions. See example screen shot below depicting an uploaded value of 1540166400000.00.

![Capture](https://user-images.githubusercontent.com/65416034/156376875-62af8bcf-0cd5-42b0-a612-16d71947c72a.PNG)
