### ISSUE TITLE
Cruise Event: Prototype Event UI

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#525]
Design and implement UI logic to show a Cruise Event and associated Cruises

**Comment by MarioCarloni** [comment]
![image](https://user-images.githubusercontent.com/5469058/157295132-501c5970-de9d-408d-a99a-45236b175f25.png)

**Comment by joannekoch** [comment]
Cruise Event implemented.
![Capture](https://user-images.githubusercontent.com/65416034/161808753-5f840b78-02f2-4947-95cf-5585178b83de.PNG)
