### ISSUE TITLE
Calibration Event: Change Calibration Date output to ISO format

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#527]
From the Inventory Detail template, modify Calibration Date outputs to the following format:

yyyy-mm-ddTHH:MM:SS

**Comment by joannekoch** [comment]
Calibration date is displayed in ISO format as depicted below.

![Capture](https://user-images.githubusercontent.com/65416034/158643105-c55717c4-bd8c-4ef4-91fd-93fd2cbe643d.PNG)
