### ISSUE TITLE
Vessel List template: Add Cruise button

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#530]
From the Vessel List template, no back button exists to navigate to the associated Cruise detail page. Create functionality for Users to navigate back to the Cruise detail template.

**Comment by joannekoch** [comment]
Cruise back button added to the Vessel screen
![Capture](https://user-images.githubusercontent.com/65416034/161777450-af2569bd-aefc-43e0-91ba-05866961e074.PNG)
.
