### ISSUE TITLE
Build Screen Missing for Uploaded Deployments

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#534]
When a Deployment is uploaded, the Build Screen is missing.

Steps to reproduce:
Upload a Deployment and navigate to the Deployment History.
![Capture](https://user-images.githubusercontent.com/65416034/159706994-6375f06f-d32f-430c-a28c-8f1c42577505.PNG)

Edit the Deployment Details and hit Cancel.

![Capture1](https://user-images.githubusercontent.com/65416034/159707284-95c53c87-2a3e-4908-a596-8d9bd2ef3316.PNG)

The Build Screen and its Choose Action menu now appears. This is the only way to get to it - as it is missing from the NavTree.

![Capture2](https://user-images.githubusercontent.com/65416034/159707559-4c828005-dfdf-471f-acaa-ef30365caba8.PNG)

**Comment by joannekoch** [comment]
@MarioCarloni, the first screenshot is the Builds navtree, the second is the Deployment Details Edit template and the third is the Build details template. This build was uploaded without a stopDateTime, so it resides in the Coastal Pioneer location. 

From the Deployment Details Edit template, if the Cancel button is clicked, the Build details page is loaded.

I may have pasted in the wrong screen shot above. Here's the correct screen shot.  The "Singer" build was created by hand and it resides in the navtree under the Test location. The "GS Surface Mooring" build was imported and is not visible under the Coastal Pioneer location in the same way as the Singer build. The question is: should they look the same in the navtree?

![Capture](https://user-images.githubusercontent.com/65416034/160682194-1d96877a-df90-4123-8a93-76ce5aca78ac.PNG)

**Comment by MarioCarloni** [comment]
Hi @joannekoch Deployment CSV rows are events grouped by mooring.uid. Setting a stop date time on a specific row will not stop a historical deployment and Build (mooring.uid) from being placed in the Retired Location. There was originally a reason we had set deployments in the retired location in the first place which I cannot remember offhand. I'll try to dig up some documentation about it and post it here.

Thanks for looking into this!
