### ISSUE TITLE
Assembly Revisions testing

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ooicgsn-roundabout#54]
@rhmunier  The rdb-testing site has been updated with the new code to implement the Assembly Revisions update. There are two separate test cases that you'll need to run through for this:

#1 - **Basic functionality for creating new Assemblies/Builds using the Assembly Revision system** 
Does it work as expected, is it intuitive to use from your perspective, etc. Expected behavior is as follows:

- When a user creates a new Assembly, an initial Revision for that Assembly is created.
- If a user creates a new Revision, the existing Assembly part design tree is copied over to the new Revision.
- If a user removes or adds a Part to the new Revision, all previous Revisions remain unchanged. Also any Build that is made from previous Revisions remains unchanged.
- If a user tries to update a Revision design with existing Builds, they are warned as before and encouraged to create a New Revision instead.
- Each Revision can have Documents linked to it like the Part templates, and the documents should be specific to each Revision.

#2 - **Backwards compatibility with your existing Assemblies/Builds/Inventory.** 
To make this new code work, we have to make a series of database migrations to existing data. These migrations have been applied to your existing Assemblies, etc. We need to test that all existing items still work as expected and contain all the appropriate data and relationships as before.

Let me know if you have any questions on any of these testing requests. Thanks for your hard work!

**Comment by rhmunier** [comment]
Almost all things are working as normal.  I am unable to add documents to templates or inventory for both assemblies or parts.

**Comment by ethanandrews** [comment]
Ok, great. I’ll take a look at the documents.

On Mar 18, 2020, at 1:00 PM, rhmunier <notifications@github.com> wrote:

﻿

Almost all things are working as normal. I am unable to add documents to templates or inventory for both assemblies or parts.

**Comment by ethanandrews** [comment]
@rhmunier I tested adding documents to both Part Templates Assembly Revisions and both seemed to work find. See attached screenshot for example. Is this what you were having problems with or was it something else?
<img width="1656" alt="Screen Shot 2020-03-18 at 2 23 22 PM" src="https://user-images.githubusercontent.com/39806262/76994113-4ffde580-6924-11ea-83bb-c752f4dbe682.png">
