### ISSUE TITLE
Deleting Location and moving Build & Inventory to Retired causes Database Issues

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#544]
When deleting a Location that has a Build & Inventory, the user is asked to specify a new location to move the Build & Inventory to.  After the location is deleted and the items are moved to the new location (i.e. Retired in this case), the following is observed:

1. Try to Create a Constant/Conifg on any Inventory (not in Retired) results in the following errors and no Create Constant screen is displayed to the user.
![Capture](https://user-images.githubusercontent.com/65416034/163243786-074c367c-a6c2-48bd-ae43-c9df0798435e.PNG)
![Capture1](https://user-images.githubusercontent.com/65416034/163243796-79eccf61-ae28-4d50-9e9d-b72cd79a4f3b.PNG)

2. Even if all the items in my local database are deleted, with exception of the Retired items (these cannot be deleted), and then the items are re-created, you still cannot Create a Constant/Config on any Inventory (not in Retired) as described above. The database seems to be corrupted.
3. Only if you perform: "docker-compose -f local.yml down -v --remove-orphans" and wipe out the database and then re-create all the items are you able to Create Constants/Configs on Inventory items.

Note: I've seen this db issue for quite a while, and only now have I been able to pinpoint the root cause.

**Comment by MarioCarloni** [comment]
This might be related to #557, regarding strange behavior when moving Inventory/Builds. My guess here is the logic that moves Inventory/Builds to a new Location needs to be updated to account for additional related objects.

**Comment by joannekoch** [comment]
This is fixed. Nice job!
