### ISSUE TITLE
Inventory: Config Events: Name context dropdowns not collapsible

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#546]
Within a Config Event, Config names are generated as dropdown contexts, containing an expander button which should either show or hide its contents. Contents are expanded by default, however, nothing happens when clicked. Please fix so that dropdown contents are expandable/collapsible.

**Comment by joannekoch** [comment]
The dropdown contents are expandable/collapsible and are working.
![Capture](https://user-images.githubusercontent.com/65416034/169363593-b145cc1c-5eb5-482e-967f-f100b0ac9e57.PNG)
