### ISSUE TITLE
Keep trailing zeros in custom Decimal fields

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ooicgsn-roundabout#55]
If a Custom Field for an Inventory item is a Decimal Field, it needs to save and display any trailing zeroes that are entered: ex. 12.20

**Comment by ethanandrews** [comment]
@rhmunier The fix for this issue is on the rdb-testing site, ready for you to test. Please confirm that it works as expected

**Comment by rhmunier** [comment]
Precision 0 are maintained, leading 0 are not but that is intentional from what I know.
