### ISSUE TITLE
Reference Designator Import: Invalid designators still imported

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#553]
On rdb-testing I had imported the vocab.csv from the Reference Designator Import field. The designator should contain 4 dash-separated sections, each varying in length. When navigating to and editing an Assembly Template, a User can associate an existing Reference Designator. However, the list still contains designators that contain less than 4 sections.

**Comment by joannekoch** [comment]
All imported Reference Designators contain 4 dash-separated sections.  Nice job!

![Capture](https://user-images.githubusercontent.com/65416034/169311449-d12cb1d1-fedf-4715-95cf-2ac0ec0295da.PNG)
