### ISSUE TITLE
Build: Deployments tab: Add "Review Requested"badge

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#554]
When a User is selected for Review regarding a Deployment, a "Review Requested" badge is shown for the associated Build Navtree item. However, when navigating to the Build details template, in a similar fashion to the other Inventory CCC Event tabs, the Deployment nav tab should display a "Review Requested" badge when a User is selected for any Deployment Review.

**Comment by joannekoch** [comment]
The Review Requested" badge on the Deployment tab is working.
![Capture](https://user-images.githubusercontent.com/65416034/169369264-8ab9541b-e3de-4fdb-bdfa-36bb306966b3.PNG)
