### ISSUE TITLE
Vocab Bulk Upload Records not matching a Part's Manufacturer and Model

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#556]
Issue #496 states: When parsing a Bulk Vocab CSV, if a row's Manufacturer and Model values match a Part's Manufacturer and Model (Custom Field) values, then associate the Bulk Upload Event with the matching Part.

As show below, there are rows in the sensor_vocab.csv which appear in the Bulk Upload Record for the Part that do not match the Part's Manufacturer and Model values.

Also, the sensor, platform, node, eng vocab files were all uploaded together in the same Bulk Upload Csv Import action. The sensor_vocab.csv file is the only vocab file that contains the Model and Manufacturer for this Part. Yet the platform, node, and eng vocab csv files also appear in the list for this part. 

![Capture](https://user-images.githubusercontent.com/65416034/149216789-07965d64-0231-4f55-9bf4-565904e9e0b6.PNG)

**Comment by MarioCarloni** [comment]
Hey @joannekoch I think we'll need @cahearn input here. Last we had discussed regarding Part Bulk Upload Events was displaying the Vocab-related Files and fields when a Part's Manufacturer/Model fieldvalues matched a CSV row. I was under the impression that all Vocab files were to be displayed for any matching Part, but could definitely be mistaken!

@cahearn would Users want all Vocab-related Files displayed for a matching Part, or would Users want only the matching row/File?

**Comment by joannekoch** [comment]
Works!  Only the vocab files where every line of the file matches an existing Part's Manufacturer and Model values are allowed to be imported. If one line of the vocab file contains a Manufacturer and Model which is NOT defined for any Part, then an import error is thrown.

When a vocab file is successfully imported, this informative message is displayed.  Very nice!

![Capture](https://user-images.githubusercontent.com/65416034/169318090-2c88c6fb-3488-46b0-ad36-786229c6d905.PNG)

The platform, node, eng vocab files no longer appear as Bulk Uploaded files because there aren't any Parts defined with the required Manufacturer and Model numbers.

![Capture](https://user-images.githubusercontent.com/65416034/169318979-6052614a-400d-444a-bfa4-819f344b6c2b.PNG)
