### ISSUE TITLE
"Add to Build" screen broken after Upload Deployment Github CSV

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#557]
Before Uploading a Deployment Github CSV file, the Inventory Choose Action->"Add to Build" screen was displayed and working.

After Uploading a Deployment Github CSV file, the Add to Build screen does not appear for any and all Inventory chosen in the navtree and the following django error is printed:
![Capture](https://user-images.githubusercontent.com/65416034/167686172-83ff6e3c-571d-46fe-8846-a7b415ed16df.PNG)

The Deployment Github CSV file uploaded: 
![Capture1](https://user-images.githubusercontent.com/65416034/167686464-db16c220-d5bc-4a13-bb21-4d5031bac63e.PNG)

Uploaded Build:

![Capture2](https://user-images.githubusercontent.com/65416034/167687090-f330cc41-5ba2-4d80-92d8-39b8dd01d194.PNG)

After, if I retire all builds, delete all inventory, assemblies, parts, and locations created from my database and then re-create these items, the Inventory Choose Action->Add to Build screen is displayed and works again. Note that deleting the assemblies removes retired builds from the retired location.
![Capture](https://user-images.githubusercontent.com/65416034/167689407-56097881-d24a-4628-9e26-79be331267a0.PNG)

**Comment by MarioCarloni** [comment]
Hi @joannekoch I am getting a similar error locally. After deleting a Location, and moving existing Inventory to another Location, I'm receiving an error when trying to load any Inventory or Build template. The error is regarding a location name not being found from the Deployment model. I'm thinking the error might have to do with associated Deployment Locations not changing over with the Inventory/Builds.

**Comment by joannekoch** [comment]
Hey @MarioCarloni, I don't think this issue to related to deleting a location and this is why. I ran this test:

- Deleted all my rdb volume data using "docker-compose -f local.yml down -v --remove-orphans" and started with a clean database.
- Ran my Automated Tests building up my database and adding locations, parts, assemblies, inventory, builds, etc.
- Periodically checked the "Add to Build" screen during the automated testing run and it was working fine.
- Uploaded my Deployment Github Csv. Checked the "Add to Build" screen and it would NOT launch as described above after the upload.

If cleaning the database with -v remove-orphans leaves crumbs in the database behind, then I could be mistaken.

**Comment by MarioCarloni** [comment]
Hey @joannekoch you had mentioned the "Add to Build" action was missing from all Inventory items? I think the "Add to Build" action should only appear for Inventory items not already associated with a Build.

**Comment by joannekoch** [comment]
@MarioCarloni the "Add to Build" action was not missing, sorry if I wasn't clear about what was happening.

When I clicked the "Add to Build" action, nothing happened - no screen is launched - and the above django error occurs.

**Comment by joannekoch** [comment]
This is fixed - nice work tracking this down!
![Capture](https://user-images.githubusercontent.com/65416034/169361496-39e782fc-735b-46aa-b5fc-c7eec72cd5ed.PNG)
