### ISSUE TITLE
Inventory: Part Revision invisible

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#558]
Example on Testing server: https://rdb-testing.whoi.edu/inventory/10104/

![image](https://user-images.githubusercontent.com/5469058/167862616-96ae75a7-def4-4d49-91f4-a661fd795d7a.png)

**Comment by joannekoch** [comment]
I'm still seeing no part revision number on my local test environment.

![Capture](https://user-images.githubusercontent.com/65416034/169314045-ace793df-45ad-4cab-84be-d0838282bcfd.PNG)

**Comment by joannekoch** [comment]
Fixed.
![Capture](https://user-images.githubusercontent.com/65416034/170129459-9bc7f7dc-7c5c-4540-882b-6191b9480c07.PNG)
