### ISSUE TITLE
Duplicate Assembly created when Uploading Deployment CSV

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#566]
Steps to Reproduce:
1. Create the following Assembly and Inventory.
![Capture](https://user-images.githubusercontent.com/65416034/170276567-38b00f25-ca6e-48c1-aec4-21dde8a6fa8a.PNG)
![Capture1](https://user-images.githubusercontent.com/65416034/170276580-bb67e4ae-5d29-499c-8172-0120356d2a6a.PNG)

2. Upload this Deployment CSV file:
![Capture](https://user-images.githubusercontent.com/65416034/170277161-e30e07a4-5a43-4019-b946-3120dc1d55a1.PNG)

3. An Additional ADCPS-J Assembly is created by the Upload when it should not have been because it already existed.
![Capture2](https://user-images.githubusercontent.com/65416034/170277773-6e58bf8a-8b72-472f-97ad-36de744e804a.PNG)

![Capture](https://user-images.githubusercontent.com/65416034/170278401-2e9e232c-d514-4f4d-8e11-3b16eb99ce65.PNG)

**Comment by joannekoch** [comment]
@MarioCarloni, I'm seeing the exact same results as shown above when I import the Deployment CSV depicted above.

**Comment by joannekoch** [comment]
Manually create Assembly ADCPS-J, Rev B. Duplicate Assembly, Rev B, is still created when uploading this Deployment CSV:
![Capture2](https://user-images.githubusercontent.com/65416034/173613622-07386612-791c-4637-9fba-9c3c7da0cb7f.PNG)

![Capture](https://user-images.githubusercontent.com/65416034/173613656-67c4e6e3-8a4b-4eb0-ba8b-68ca3479fbba.PNG)
![Capture1](https://user-images.githubusercontent.com/65416034/173613674-41fcb90e-44a7-4f21-ab80-f1f872af7a05.PNG)

**Comment by MarioCarloni** [comment]
Hey @joannekoch, by chance did your manually created part have a "Friendly Name"?

There are two places where assembly parts are created in the deployment import code. One of them relies on the Name (or Friendly Name if available) of the Inventory item's Part.

During bulk import, parts can be created if not existing, however only the part name and number are filled, while the friendly name is left to the user. I wonder if there is any data in the file name or file metadata we can use to set the part friendly name?

**Comment by joannekoch** [comment]
Hi @MarioCarloni, my manually created part did not have a Friendly Name.
![Capture](https://user-images.githubusercontent.com/65416034/173836529-da7f9794-7a95-4209-80c7-dade420a19ca.PNG)

**Comment by joannekoch** [comment]
Hi @MarioCarloni, this is looking better. The manually created Inventory is on the uploaded build where it should be.
There are still duplicate assemblies (one manually created and one created by the upload), but now they are both on a Build. The manually created assembly is on the uploaded build, but the duplicate assembly is on an unnamed build (see below). 
![Capture](https://user-images.githubusercontent.com/65416034/173880014-2a4609c3-a9cd-4a6a-b043-e85f8c5935fb.PNG)
![Capture](https://user-images.githubusercontent.com/65416034/173881216-b368c85e-8367-4c98-8ddf-461191ef53c1.PNG)
![Capture](https://user-images.githubusercontent.com/65416034/173880041-74e42683-1308-4dbb-9d58-910cd4fb6075.PNG)
![Capture2](https://user-images.githubusercontent.com/65416034/173880052-93995c00-c6ea-42ec-aba2-9f639ea6e375.PNG)
