### ISSUE TITLE
Deployment Import: Commented rows still imported

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#568]
Certain rows in Deployment CSV's, containing sensors with Reference Designators not yet used, are commented out. Commented out rows should be skipped, however they are still being read and validated against. 

In RDB, a validation error is thrown, referencing CP03ISSM-RID27-07-SPKIRB000 not being found. The associated CSV row is commented out, so no validation errors should occur either. Please fix so that commented rows are skipped.

**Comment by joannekoch** [comment]
Works. Commented out rows are skipped and are not being read and validated.
