### ISSUE TITLE
Notes do not allow .txt as valid file upload

### ISSUE THREAD

**Issue by rhmunier** [WHOIGit/ooicgsn-roundabout#57]
When adding a note to an inventory item or build, the upload element does not accept .txt files nor does it give a validation or error message.  The element should either have a message added or changed to allow .txt files if there are plans of their use.

**Comment by ethanandrews** [comment]
Hey @rhmunier, please test out the file upload validation again. .txt files are still not allowed, but you should now get a validation error message displayed. Please test both Inventory and Build notes. Thanks!

**Comment by rhmunier** [comment]
Error message works as intended for both items with a list of acceptable file formats
