### ISSUE TITLE
Bulk Upload Tool Allows Deployed Inventory Location Change 

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#579]
Normally, through the UI the user cannot change the location of a Deployed Inventory. The Bulk Upload Tool allows Deployed Inventory location change with inconsistent results.  When a Deployed Inventory, Coastal Mooring, was uploaded with the Bulk Upload Tool and a new location was specified (Test1), the import was valid and no error was displayed. The old location (Test) of the Deployed Inventory was not changed in the navtree, but the Inventory detail shows the new location.
![Capture](https://user-images.githubusercontent.com/65416034/176440672-5d2253a4-7e8c-4343-94d6-e3cb4dbb1c9d.PNG)

**Comment by joannekoch** [comment]
This sequence of events results in TypeError screen:
1. End a Deployment on a Build.
2. Start Deployment, Initiate Burn-in, Deploy to Field the same Build as above. 
3. Bulk Upload an Inventory (assigned to the above build) csv file with a new location.
4. Receive this warning screen.
![Capture1](https://user-images.githubusercontent.com/65416034/178344812-36a5d999-2c5e-4c93-b9d5-d654fc368c68.PNG)
5. Click to Complete the Import and get this TypeError:
![Capture](https://user-images.githubusercontent.com/65416034/178344903-a3706566-45f7-490d-a7c7-c10f0e6996cc.PNG)

**Comment by joannekoch** [comment]
Bulk upload the Inventory CSV file and get this screen (without even getting the import preview screen):
![Capture](https://user-images.githubusercontent.com/65416034/180257349-ca90e0da-8cbc-4112-85d6-03c2b576b44e.PNG)

This is my Inventory CSV file:

![Capture1](https://user-images.githubusercontent.com/65416034/180257451-6c3cf550-47ae-4740-a4b0-ffdc9b9ffbc5.PNG)

This is my Inventory:

![Capture2](https://user-images.githubusercontent.com/65416034/180257511-eec01c11-65be-41db-bce4-81b0363702ce.PNG)

**Comment by joannekoch** [comment]
Hey Mario, I'm still getting the same attribute error in both cases:

-  when the Build is newly created and deployed
-  and also when the same Build has been ended and re-deployed.

![Capture](https://user-images.githubusercontent.com/65416034/180825982-76cd68b2-f9c5-4351-bca2-01bf00838cd7.PNG)

I'm using the same data outlined above.

**Comment by joannekoch** [comment]
The attribute error is fixed and the Inventory csv file above was imported successfully. There are a few things with the import to note, see below.
Here is a snapshot of the Inventory/Builds before the import.
![Capture](https://user-images.githubusercontent.com/65416034/181057199-0e157d67-e002-4305-981a-3a42740e0218.PNG)
This is the import preview screen. Note that CGINS-ADCPSJ-19062 is not on a Build, but the import preview screen states that it is on a build.
![Capture1](https://user-images.githubusercontent.com/65416034/181057383-e08b2e03-e11f-4b39-9b22-aa701d47e179.PNG)
This is the Inventory/Build screen after the import. Note that the GS Surface Mooring Build and the Salty Reef Builds were not Retired, the builds were Ended.  This contradicts what the import preview states. Also note that the 3 inventory items that were imported were correctly moved to the Test1 location as specified in the Import Csv file. 
![Capture2](https://user-images.githubusercontent.com/65416034/181058203-81d0876f-a4bb-4ebd-9896-1366fc2d31ea.PNG)
Also note that buoy and wifi Inventory items appear in two places in the navtree. I think we need to decided how we are going handle sub-assemblies of moved Inventory items. They appear in the Test (see previous screen shot) and Test1 locations, but the Inventory details has them in the Test Location. It is interesting to note that when the surface mooring inventory is expanded in the Test location, then the surface mooring inventory is collapsed in the Test1 location, and when the surface mooring inventory is expanded in the Test1 location, it is collapsed in the Test location.
![Capture3](https://user-images.githubusercontent.com/65416034/181059551-91aa6654-3aee-4dd6-af38-9c5c8fdf89f8.PNG)

**Comment by MarioCarloni** [comment]
Hey @joannekoch awesome work chasing this down!

**Comment by MarioCarloni** [comment]
Hi @joannekoch thanks for your work on this. I am unable to move forward with this functionality, and will revisit at a later time.

**Comment by joannekoch** [comment]
The problem with moving Inventory on a Build has been resolved, however, CGINS-ADCPSJ-19062, is NOT on a Build
and an error was flagged when it should not have been.

![Capture](https://user-images.githubusercontent.com/65416034/187517140-fd8841c0-54f4-4574-8b0e-1fc746394b42.PNG)

**Comment by joannekoch** [comment]
As noted above, CGINS-ADCPSJ-19062, is NOT on a Build and the Bulk Upload Inventory is thowing this attribute error:

![Capture](https://user-images.githubusercontent.com/65416034/188895103-495c750f-b382-48f3-b251-3f771b92d0e7.PNG)

**Comment by joannekoch** [comment]
Getting closer....  1232-20001 and CGINS-ADCPSJ-19061 are on a Build, CGINS-ADCPSJ-19062 is not on a Build.
1232-20001 and  CGINS-ADCPSJ-19062 are flagged correctly,  but CGINS-ADCPSJ-19061 is not flagged correctly for error because it is on a Build and there is no error (see below).

![Capture](https://user-images.githubusercontent.com/65416034/188936531-7e6d6419-7454-4cdc-aea9-6c9501ae5bd6.PNG)
![Capture1](https://user-images.githubusercontent.com/65416034/188936551-c23b44be-254b-470a-abcf-ee1328f2dee1.PNG)

**Comment by joannekoch** [comment]
The error above is not fixed. Moving this back to In Progress.

**Comment by joannekoch** [comment]
The Deployed validation error checking is working correctly. 1232-20001 and CGINS-ADCPSJ-19061 are on a Build and therefore their locations cannot be changed.  Nice job!

![Capture](https://user-images.githubusercontent.com/65416034/191578289-f15ff6d2-77ae-4170-a59c-1022778003f8.PNG)
