### ISSUE TITLE
Bulk Upload Tool: Bulk Inventory: Existing Parts are queried against "Inventory" only

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#587]
During Bulk Inventory import, Parts are either queried or generated based on the Part Number and Part Type: "Instrument". While a single Part Type is required for Part generation, existing Parts may be of any type, and not just "Instrument". Please fix so that, during Part querying, existing Parts search through all Part types as well as the Part Number.

**Comment by joannekoch** [comment]
Hey @MarioCarloni, please let me know the best way to test this. I'm not sure what Part Type: Inventory is.

**Comment by MarioCarloni** [comment]
Hey @joannekoch , you're right, there is no inventory part type. I meant "Instrument", and will edit the ticket.

Basically, the importer now looks for Parts using the Part Number, as well as all known Part Types (Instrument, Electrical etc)

**Comment by joannekoch** [comment]
This is working. Was able to upload an Inventory when it's part type is "Cable". The Inventory was created successfully.
Part Type Cable:
![Capture](https://user-images.githubusercontent.com/65416034/187678894-7be520e0-b819-4acf-83e6-899aafadb55c.PNG)
The upload created a new Inventory:
![Capture1](https://user-images.githubusercontent.com/65416034/187678964-4b3fa131-0702-4514-819f-1e243b95aa6b.PNG)
Upload file:
![Capture2](https://user-images.githubusercontent.com/65416034/187678978-5c74387c-0c61-4f9f-a182-6a6dbbb18d45.PNG)
