### ISSUE TITLE
Bulk Upload: Deployment Import validation: Handle Duplicate Reference Designators

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#588]
An error was thrown when attempting to import a Deployment CSV. During validation, a Reference Designator object is queried, and several error-cases are handled. However, duplicate records are not. Please update the validation routine so that, in the case where duplicate Reference Designators exist, only one Reference Designator is queried,

**Comment by joannekoch** [comment]
This is working. 

Method to test: 
1. Assigned the same reference designator to two different Assemblies. One of the Assemblies' ID Number is set to the first section of the reference designator.
2. Bulk Uploaded a Deployment csv file.
3. The upload was successful, did not issue an error, and created a Deployment in the proper location.
