### ISSUE TITLE
Bulk Upload Tab missing from Inventory

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#600]
Created this Inventory:
![Capture](https://user-images.githubusercontent.com/65416034/189168543-d47f67ec-95e7-4bfe-ad6a-c2ffdd3c4e1b.PNG)

Bulk Uploaded this sensor_bulk_load-AssetRecord.csv
![Capture1](https://user-images.githubusercontent.com/65416034/189168584-34d243ac-a7ee-476f-9a21-002bc7afa5b8.PNG)

The import was sucessful and you will note that the Bulk Upload Tab is missing from the Inventory:

![Capture](https://user-images.githubusercontent.com/65416034/189169031-ade1e310-33e9-4de8-9f58-b3ecbbc5d30c.PNG)

Note that this automated test was working on Github package #100. Hopefully this helps.

**Comment by MarioCarloni** [comment]
Hey @joannekoch, thanks again for chasing this down. I have a few questions surrounding the test.

How did you originally create the Inventory item ADCPSJ-19061? VIa the UI's "Add Inventory", or through the Bulk Upload tool?
![image](https://user-images.githubusercontent.com/5469058/191330593-23cf2641-780d-4729-85d7-a5aa417bf849.png)


Do you notice the issue happening for Inventory items generated prior to Bulk CSV import? Do you notice the issue across Inventory items, generated during Bulk CSV import, that didn't exist prior as well?

**Comment by joannekoch** [comment]
@MarioCarloni -  I'm also seeing this: When the Part and Inventory does not exist and I upload the the sensor_bulk_load-AssetRecord.csv shown above via Upload Github CSV's, the Part and Inventory are NOT created. This used to work - The Part was created because the rdb_part_template is supplied and the Inventory was created in "Retired".

**Comment by MarioCarloni** [comment]
Hey @joannekoch I was looking at recently failed Actions https://github.com/WHOIGit/ooicgsn-roundabout/actions/runs/3010283779/jobs/4836209018 and noticed there's a Validation error thrown from the app, regarding a missing Manufacturer value from the sensor_vocab.csv. However, I'm not seeing this error from rdb-testing.

**Comment by ethanandrews** [comment]
Hey Joanne

Can you tell Mario why the latest Action run failed:

https://github.com/WHOIGit/ooicgsn-roundabout/actions/runs/3184109094



From: Joanne Koch ***@***.***>
Date: Tuesday, October 4, 2022 at 11:43 AM
To: WHOIGit/ooicgsn-roundabout ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [WHOIGit/ooicgsn-roundabout] Bulk Upload Tab missing from Inventory (Issue #600)

Hi @MarioCarloni<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarioCarloni&data=05%7C01%7Ceandrews%40whoi.edu%7Ca8627b19c26742b241dd08daa61f20ea%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C638004949877174750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bBQhU46aQSpQfi8QXAihbEWdPIC0QRiDGjAXUTtx2B8%3D&reserved=0>, that failed Action is old. Please look at the most recent: https://github.com/WHOIGit/ooicgsn-roundabout/actions/runs/3151710243/jobs/5126009474 and you will see that the sensor_vocab.csv upload is successful:

"Sensor_vocab.csv bulk upload successful. Vocab.csv bulk upload successful. no such element: Unable to locate element: {"method":"css selector","selector":"*[id="bulkupload-template-tab"]"} "

Let me know if you have any more questions or trouble reproducing the issue.

**Comment by joannekoch** [comment]
Hey @MarioCarloni - you solved the issue!  The Automated Tests were successful and the Build was tagged & published. Thanks for your efforts!  I will get the fix and test in my local environment as an added check.
