### ISSUE TITLE
Legacy Cruises do not have associated Cruise Events

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#615]
Cruises created prior to the Event system do not have associated Cruise Events. Create logic to generate Cruise Events and associate them with Cruises without Events.

**Comment by joannekoch** [comment]
Hey @MarioCarloni, any ideas on how I could test this?

**Comment by ethanandrews** [comment]
This is a limited use, one-time function so I don’t think it’s necessary to create a test for it.

From: Joanne Koch ***@***.***>
Date: Monday, November 7, 2022 at 9:38 AM
To: WHOIGit/ooicgsn-roundabout ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [WHOIGit/ooicgsn-roundabout] Legacy Cruises do not have associated Cruise Events (Issue #615)

Hey @MarioCarloni<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarioCarloni&data=05%7C01%7Ceandrews%40whoi.edu%7C0dd2c56516424bc8c66108dac0cdb822%7Cd44c5cc6d18c46cc8abd4fdf5b6e5944%7C0%7C0%7C638034287060374955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IRfyw2LiAoLfAH9ivtd6XvobS96Fd3LjrOEy3xYOLKQ%3D&reserved=0>, any ideas on how I could test this?
