### ISSUE TITLE
Cruise UI: Detail contents spill outside of container

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#617]
Within the Cruise Event Detail template, details will begin spilling out of the Event content box. Please fix so that inner contents stay within the parent boundaries.

**Comment by joannekoch** [comment]
All Cruise event details are now visible.

![Capture](https://user-images.githubusercontent.com/65416034/200336523-31510101-7086-49a7-abf9-f543b341d517.PNG)
