### ISSUE TITLE
Delete Bulk Upload Part Template results in Spinning Wheel

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#624]
Steps to reproduce:

1. Upload Github Csv, Bulk Upload all AssetRecord csv files.  The result is multiple Inventory are created in Retired and one new Part Template ( Acomms-DUBO_343_Science Bay) is created.
2. Delete  Acomms-DUBO_343_Science Bay that was created by the Bulk Upload.
3. Result is a Spinning Wheel that never goes away.
![Capture](https://user-images.githubusercontent.com/65416034/202260271-c841eb9a-48ab-4ca8-b3ce-0478ac30117a.PNG)

**Comment by MarioCarloni** [comment]
Based on the duplicated Part template value in all Bulk AssetRecord CSV's in the Test Asset Management repo, deleting the Part causes all Inventory items on the system to simultaneously delete. When there is a diverse Part set, and a Part is deleted, only a subset of related Inventory items are deleted.

**Comment by joannekoch** [comment]
The spinning wheel does not persist, so this issue is fixed.
