### ISSUE TITLE
OOI Prod Inventory views are broken for select Inventory Items

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#640]
CGINS-PARADJ-00411 is throwing a "NoReversMatch" error, here - https://ooi-cgrdb.whoi.net/inventory/3127/

![image](https://user-images.githubusercontent.com/14059724/223202974-2cf99ce6-840a-4857-a7f8-103116e69ff4.png)

Previously saw similar behavior for these as well, but something has changed since originally reported around 2/3/23:

CGINS-CTDPFJ-00346  -  https://ooi-cgrdb.whoi.net/inventory/3098

CGINS-PARADJ-00504  -  https://ooi-cgrdb.whoi.net/inventory/3130/

**Comment by ethanandrews** [comment]
I've fixed the immediate issue with broken link. Further investigation is needed to determine how that happened, but marking this as closed.
