### ISSUE TITLE
Deployment Bulk Import: Ensure InventoryDeployment generation

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#646]
Deployments and associated objects generated from the Deployment Bulk Import functionality are working, with the exception of InventoryDeployments.

Inventory items, currently part of a Deployment, should have a Deployment tab displaying the InventoryDeployment event and associated info.

**Comment by joannekoch** [comment]
Uploaded Github CSV's, Deployment CSV, CP04OSSM_Deploy.csv on Inventory CGINS-ADCPSJ-19061.

Verified that the Inventory item, has a "Deployments" tab displaying the InventoryDeployment event and associated deployment info.
![Capture](https://github.com/WHOIGit/ooicgsn-roundabout/assets/65416034/8053a4ca-8212-4c8a-a10e-ad5fd152563f)
