### ISSUE TITLE
File Upload through Notes is Broken

### ISSUE THREAD

**Issue by cahearn** [WHOIGit/ooicgsn-roundabout#658]
D. Neiman at OSU reported a problem with uploading a PDF to OOI Prod RDB.  I have tested and found the same on both 1.6.3 and 1.7.0

Link to example of previous successful upload
https://rdb-demo.whoi.edu/inventory/1192

Note Button
![image](https://github.com/WHOIGit/ooicgsn-roundabout/assets/14059724/d6ec87cf-4d0f-4b50-85fe-830b82d3a8d9)

Example of previous successful upload
![image](https://github.com/WHOIGit/ooicgsn-roundabout/assets/14059724/532f1c67-035b-462e-8f79-384162625962)

**Comment by MarioCarloni** [comment]
From Sentry:

![image](https://github.com/WHOIGit/ooicgsn-roundabout/assets/5469058/5074bb80-76be-4fd8-adea-75337655207b)

**Comment by ethanandrews** [comment]
Thanks for tracking that down Mario. I think is a server-side issue. I’ll take a look at the server directory permissions.


From: Mario Carloni ***@***.***>
Date: Wednesday, February 28, 2024 at 1:03 PM
To: WHOIGit/ooicgsn-roundabout ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [WHOIGit/ooicgsn-roundabout] File Upload through Notes is Broken (Issue #658)
This email originated outside of WHOI. Please use caution if clicking on links or opening attachments.

From Sentry:

image.png (view on web)<https://github.com/WHOIGit/ooicgsn-roundabout/assets/5469058/5074bb80-76be-4fd8-adea-75337655207b>

**Comment by ethanandrews** [comment]
Issue is fixed by correcting directory ownership on the VM
