### ISSUE TITLE
Adding Calibration Fields to a new Part Template is unclear

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ooicgsn-roundabout#75]
When creating a new Part, it is not clear where/how to add/edit Calibration fields.
Currently this is done by clicking on "Choose Action: Edit Part Template" dropdown on a Part of type "Inventory". This pretty unclear. 

I have suggestions:

(1) when creating a part, when updating the Part Type to "Instrument", have the page update with the interface for adding calibrations right away. Changing Part Type away from "Instrument" removes calibration fields from the interface, but going TO "Instrument" does not bring it up/back.
(1+) instead of only having calibrations on PartType "Instrument", during Part creation have a checkbox that says "enable calibrations fields" or somesuch. 

(2) In the "Choose Action" dropdown, add "Add/Remove Calibration Fields" as an option. For clarity this would probably mean removing the interface from the "Edit Part Template" page?

(3) Add a "Add New Calibration Field" button similar to "Add New Field" for Custom Fields. An interface to add one Calibration Field would appear and get populated to the list. It could then be edited or removed in a similar way to Custom Fields directly above.

![image](https://user-images.githubusercontent.com/44208509/83068147-d544fb00-a035-11ea-8f09-2f4df6585077.png)

I like (3) for the clarity and consistency of it, esp. since Custom Fields can NOT currently be specified during Part Creation, but it's also the most involved in terms of updating the interface.

I think (1) is probably the easiest to accomplish. The Part creation/edit page just needs to update when "Instrument" or (1+) enable calibrations fields checkbox is toggled-on.

And I think (2) is a happy medium, but if we go this route I think "Add New Field" from Custom fields should also be moved to "Choose Action" and renamed "Add/Remove Custom Fields" for consistency. 

Thougths?

**Comment by MarioCarloni** [comment]
Calibration UI design has been updated to include an "Add Calibration" button, as well as a new form to handle standalone Calbrations Names.
