### ISSUE TITLE
Add Cancel Button to Add and Update Screens

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#76]
Cancel Button needs to be added to all Add and Update Screens for the following: Types, Printers, Assemblies, Parts, Locations, Inventories, Deployments, Sub-Assemblies, and Builds.

The addition of the Cancel Button will satisfy the Use Case of a User exiting an add or update screen and returning to the previous screen.

**Comment by ethanandrews** [comment]
@joannekoch Cancel Buttons have been added for all forms, please test out on staging. Thanks!

**Comment by joannekoch** [comment]
Cancel buttons still missing from the following Action choices for existing Inventories: Add Sub-Assembly, Add to Parent Assembly, Add to Build, and Assign Destination.  For Builds the following action choices are missing cancel buttons: Photo/Note, Generate Report, Take Snapshot, 

All other screens have cancel buttons and they work perfectly - a very nice feature.
