### ISSUE TITLE
Search Part Template for Name returns inconsistent results

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#78]
When a search is performed on Part Templates for Name equals or contains, the results display the Name column, but when a Friendly name is defined, the search displays the Friendly name. When a Friendly name is not defined, the search displays the Name of the Part Template.

If a Part Template has a Name = "test part template" and a Friendly name = "tester", search for name contains "test" returns "tester" result. Search for name equals "test" returns nothing. Search for name contains and equals "tester" returns nothing.

**Comment by ethanandrews** [comment]
@sbatchelder Hey Sidney, can you take a look at this bug report from Joanne? Thanks!

**Comment by sbatchelder** [comment]
Aha! Yes I know what's going on here. Will fix

**Comment by joannekoch** [comment]
Thanks so much Sidney!


Joanne

________________________________

**Comment by ethanandrews** [comment]
@joannekoch Hey Joanne, Sidney has put in a fix for this and her new code is now on the staging server. Can you test out and confirm it fixes your bug? Thanks!

**Comment by joannekoch** [comment]
Will do.

Joanne

________________________________

**Comment by joannekoch** [comment]
Sidney's new code works perfectly and does fix this bug. Great job and thank you so much!
