### ISSUE TITLE
Part Template Added when validation error is displayed

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#79]
When you add a new Part Template and enter a non-unique Part Number, a validation error is displayed: Part Number already in use! Part Number must be unique. The Part Template is added with a non-unique Part Number, despite the validation error.

**Comment by ethanandrews** [comment]
@joannekoch Validation for unique Part Number is now enforced at DB level. On staging for testing

**Comment by joannekoch** [comment]
Testing on staging server found that non-unique Part Numbers are allowed. 

Unique Part Numbers are not enforced.
