### ISSUE TITLE
Invalid Location Parent/Child Assignment hangs Software

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#82]
When a Child Location changes its parent to itself, the software hangs with a spinning indicator and no error message.

When a Parent Location changes its parent to that of its child, the software hangs with a spinning indicator and no error message.

**Comment by ethanandrews** [comment]
@joannekoch Validation check added to form to show user error message. On staging for testing

**Comment by joannekoch** [comment]
Verified validation check added.
