### ISSUE TITLE
Delete Part Type invalidates associated Part Templates

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/ooicgsn-roundabout#86]
When a Part Type is deleted, the Part Templates that have been created with that Part Type are modified as such (no warning message is displayed):
- The Part Type in the Part Template is set to "none".  Part Type is a required field and none should not be valid.
- The Part Template is removed from the Part Template display tree and the Part Template can only be found with a Search.

**Comment by joannekoch** [comment]
The same behavior happens with Assembly Templates.

**Comment by cahearn** [comment]
Great Additions!: Warning and Required Reassignment of Part Templates to different Part Type will help a lot.
However, I was able to subvert your foolproof plan by selecting the Part Type I was deleting from the Reassignment list.  Devilishly clever, I know.

![image](https://user-images.githubusercontent.com/14059724/102680713-be5c2680-4188-11eb-8fe2-7a82cc6d6ea0.png)

![image](https://user-images.githubusercontent.com/14059724/102680678-750bd700-4188-11eb-9157-031fd010bef2.png)

**Comment by ethanandrews** [comment]
@cahearn this loophole has been plugged

**Comment by cahearn** [comment]
Tested on Staging just now and was able to delete AUV Assembly Template Type, orphaning the "Pretend Parts" Assembly.  :(

![image](https://user-images.githubusercontent.com/14059724/103809281-41093080-5027-11eb-9746-3d89d5770d38.png)

**Comment by ethanandrews** [comment]
My bad, only did this for Part Types, forgot Assembly Types. Should be all set for both Part and Assembly now.

**Comment by cahearn** [comment]
All good!
