### ISSUE TITLE
Cruise deployment validation issues

### ISSUE THREAD

**Issue by rhmunier** [WHOIGit/ooicgsn-roundabout#87]
The ICES, MMSI, and IMO IDs do not check for the right number of characters either too many or too few with the exception of MMSI limited to less than 2 billion something but still allows for 10 characters.

The vessel physical stats allow for negative values.

Cruise stop dates can be set to before the start date.

**Comment by rhmunier** [comment]
I am not sure if this is a bug or a feature but vessels can be part of multiple cruises with overlapping time periods.

**Comment by ethanandrews** [comment]
@rhmunier All validation fixes (ignoring the overlapping time periods, we'll consider that a non-issue) for this issue are up on rdb-testing, please check them out. Thx.
