### ISSUE TITLE
Allow Constant Defaults to be entered for the Part Inventory item at any point after creation of that Inventory item

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#94]
I've gone through a few revs of iteas on how to handle Constants, based on talking directly with Rebecca, getting feedback from Connor, and testing it myself to understand how all of the pieces currently fit together.

The concept I'm going for here is to be able to capture Constants (you can think of these as instrument-vendor-supplied constants) that are innately tied to a serial-numbered instrument and do not change (except for corrections). We need to be able to capture these before the instrument is deployed, and the values can be considered "defaults". The need to assign constants to a deployment date is just a figment of how the CI system currently works, so that is why we need to still maintain the complexity of assigning Constant "Events" to deployment dates, even though the constant values will always be the same for all deployments. We're not too far off. Here's my take on the updates needed to implement this...

Constants need to be partially differentiated from Configurations so that Constant _Default_ values can be entered pre-Initial Deployment. We should be able to enter Constant Default values during and after the creation of an Inventory item, and allow them to be corrected/updated as needed (with Review/Approval functionality).

We should keep the association of Constant _Events_ with Deployment Dates, and that functionality can stay where it is (only being unlocked upon Initial Deployment). All Constant Values for an Event can be auto-populated with the Constant Defaults and should NOT be editable from the Event.

Edits/corrections/updates to Constants would need to happen to the Defaults. We could add an "Edit Constant Default Values" button to the Event that would take you to the correct place to do that, with a _warning_ that it would update the Constant Values for ALL past/present/future Constant Events for that Inventory item.

This should capture my latest take on this... sorry it has changed so many time in the past week!!

**Comment by MarioCarloni** [comment]
https://github.com/WHOIGit/ooicgsn-roundabout/tree/cal_reviewers

**Comment by spetillo** [comment]
https://github.com/WHOIGit/ooicgsn-roundabout/tree/cal_reviewers

**Comment by spetillo** [comment]
This all seems to work. Cool!
