### ISSUE TITLE
Calibration Events: Coefficient Metadata: Implement selection-based editing for 2D arrays.

### ISSUE THREAD

**Issue by MarioCarloni** [WHOIGit/ooicgsn-roundabout#97]
2D Coefficient Metadata edit functionality should be enabled when one or more 2D Coefficient Value is selected within a Calibration Event.

![image](https://user-images.githubusercontent.com/5469058/85895001-d0ee3800-b7c3-11ea-98c7-761149fffcf5.png)

**Comment by joannekoch** [comment]
I don't see the Edit Coefficient Metadata button for this 2D Coeff. that I defined on rdb-testing.whoi.edu.

![Capture](https://user-images.githubusercontent.com/65416034/126535327-59d28148-256f-47e5-8e9f-3b9adb16bce3.PNG)

**Comment by MarioCarloni** [comment]
I was able to see the Coeffcicient Metadata Edit button by individually clicking on Coefficients within the table.
![image](https://user-images.githubusercontent.com/5469058/127048856-9c5dea1d-1722-49a5-a13a-531aaaee1b16.png)
