### ISSUE TITLE
Change "Edit Coefficient Values" page to automatically show one box for each available calibration name

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#98]
In the "Edit Coefficient Values" page for a new Calibration Event, users currently need to select a Calibration Name from the dropdown to enter a value and use the "+ Add Coefficient" link to bring up another box to select another Calibration Name to enter a value for. Instead, since each Calibration Name is required by CI to have its coefficient value filled, we should automatically show one set of Value & Notes entry boxes for each available Calibration Name. This reduces lots of extra clicking and selecting.

Edit: as Connor put much more succinctly, "Eliminate choosing Cal Coeff from dropdown at entry in Inventory Item.  Instead, pre-load one field for each of the Coeffs from the Part Template."

**Comment by MarioCarloni** [comment]
Changes for this enhancement are now testable on Staging.

**Comment by spetillo** [comment]
These changes in v1.4 on Staging look good to me.
